const crypto = require("crypto");
const FeedbackCollection = require("../models/FeedbackCollection");

const ALLOWED_TYPES = new Set(["short_text", "long_text", "email", "number", "rating", "single_choice", "multiple_choice"]);

function normalizeQuestions(questions = []) {
  return (Array.isArray(questions) ? questions : []).map((q) => ({
    id: q.id || crypto.randomUUID(),
    type: ALLOWED_TYPES.has(q.type) ? q.type : "short_text",
    label: String(q.label || "").trim().slice(0, 500),
    required: Boolean(q.required),
    options: Array.isArray(q.options) ? q.options.map((v) => String(v).trim().slice(0, 200)).filter(Boolean).slice(0, 20) : [],
  })).filter((q) => q.label).slice(0, 50);
}

function visible(collection) {
  return {
    _id: collection._id,
    title: collection.title,
    description: collection.description,
    kind: collection.kind,
    googleFormUrl: collection.googleFormUrl,
    questions: collection.questions,
    anonymous: collection.anonymous,
    preventDuplicate: collection.preventDuplicate,
    status: collection.status,
    startDate: collection.startDate,
    endDate: collection.endDate,
    promptOnLogin: Boolean(collection.promptOnLogin),
    requireOnLogin: Boolean(collection.requireOnLogin),
    promptFrequencyDays: Number(collection.promptFrequencyDays || 7),
    autoGenerated: Boolean(collection.autoGenerated),
    createdAt: collection.createdAt,
    responseCount: collection.responses?.length || 0,
  };
}

function validatePromptSettings({ promptOnLogin, requireOnLogin, kind }) {
  if (requireOnLogin && !promptOnLogin) {
    throw new Error("A required login feedback request must also be enabled for login prompts.");
  }
  if (requireOnLogin && kind !== "native") {
    throw new Error("Only native feedback can be required before portal access.");
  }
}

exports.list = async (req, res) => {
  const filter = req.user.role === "member" ? { status: "active" } : {};
  const docs = await FeedbackCollection.find(filter).sort({ createdAt: -1 });
  res.json({ success: true, collections: docs.map(visible) });
};

exports.create = async (req, res) => {
  try {
    const { title, description, kind, googleFormUrl, questions, anonymous, preventDuplicate, status, startDate, endDate, promptOnLogin, requireOnLogin, promptFrequencyDays, autoGenerated } = req.body || {};
    if (!String(title || "").trim() || !["native", "google_form"].includes(kind)) {
      return res.status(400).json({ success: false, message: "Title and a valid feedback type are required." });
    }
    if (kind === "google_form" && !/^https:\/\//i.test(String(googleFormUrl || ""))) {
      return res.status(400).json({ success: false, message: "A secure Google Forms HTTPS URL is required." });
    }
    if (kind === "native" && !Array.isArray(questions)) {
      return res.status(400).json({ success: false, message: "Native feedback questions are required." });
    }
    validatePromptSettings({ promptOnLogin: Boolean(promptOnLogin), requireOnLogin: Boolean(requireOnLogin), kind });
    const doc = await FeedbackCollection.create({
      title: String(title).trim().slice(0, 160), description: String(description || "").trim().slice(0, 2000), kind,
      googleFormUrl: kind === "google_form" ? String(googleFormUrl).trim() : "",
      questions: kind === "native" ? normalizeQuestions(questions) : [], anonymous: Boolean(anonymous),
      preventDuplicate: preventDuplicate !== false, status: ["draft", "active", "closed"].includes(status) ? status : "active",
      startDate: startDate || null, endDate: endDate || null,
      promptOnLogin: Boolean(promptOnLogin), requireOnLogin: Boolean(requireOnLogin),
      promptFrequencyDays: Math.max(0, Math.min(3650, Number(promptFrequencyDays ?? 7) || 0)),
      autoGenerated: Boolean(autoGenerated),
      createdBy: req.user._id, createdByRole: req.user.role,
    });
    res.status(201).json({ success: true, collection: visible(doc) });
  } catch (error) {
    res.status(400).json({ success: false, message: error.message });
  }
};

exports.update = async (req, res) => {
  try {
    const doc = await FeedbackCollection.findById(req.params.id);
    if (!doc) return res.status(404).json({ success: false, message: "Feedback collection not found." });
    const allowed = ["title","description","googleFormUrl","questions","anonymous","preventDuplicate","status","startDate","endDate","promptOnLogin","requireOnLogin","promptFrequencyDays","autoGenerated"];
    for (const key of allowed) {
      if (req.body[key] === undefined) continue;
      doc[key] = key === "questions" ? normalizeQuestions(req.body[key]) : req.body[key];
    }
    validatePromptSettings({ promptOnLogin: Boolean(doc.promptOnLogin), requireOnLogin: Boolean(doc.requireOnLogin), kind: doc.kind });
    if (doc.googleFormUrl && doc.kind === "google_form" && !/^https:\/\//i.test(doc.googleFormUrl)) {
      return res.status(400).json({ success: false, message: "Google Forms URL must use HTTPS." });
    }
    await doc.save();
    res.json({ success: true, collection: visible(doc) });
  } catch (error) {
    res.status(400).json({ success: false, message: error.message });
  }
};

exports.remove = async (req, res) => {
  const doc = await FeedbackCollection.findByIdAndDelete(req.params.id);
  if (!doc) return res.status(404).json({ success: false, message: "Feedback collection not found." });
  res.json({ success: true, message: "Feedback collection deleted." });
};

exports.pendingLogin = async (req, res) => {
  if (req.user.role !== "member") return res.json({ success: true, prompt: null });
  const now = new Date();
  const docs = await FeedbackCollection.find({
    kind: "native", status: "active", promptOnLogin: true,
    $and: [{ $or: [{ startDate: null }, { startDate: { $lte: now } }] }, { $or: [{ endDate: null }, { endDate: { $gte: now } }] }],
  }).sort({ requireOnLogin: -1, createdAt: -1 });
  for (const doc of docs) {
    const alreadyAnswered = doc.responses?.some((r) => String(r.member || "") === String(req.user._id));
    if (alreadyAnswered && doc.preventDuplicate) continue;
    return res.json({ success: true, prompt: visible(doc), required: Boolean(doc.requireOnLogin) });
  }
  return res.json({ success: true, prompt: null, required: false });
};

exports.submit = async (req, res) => {
  const doc = await FeedbackCollection.findById(req.params.id);
  if (!doc || doc.status !== "active") return res.status(404).json({ success: false, message: "Feedback collection is not available." });
  const now = new Date();
  if (doc.startDate && now < doc.startDate) return res.status(400).json({ success: false, message: "Feedback collection has not started yet." });
  if (doc.endDate && now > doc.endDate) return res.status(400).json({ success: false, message: "Feedback collection has closed." });
  if (doc.kind !== "native") return res.status(400).json({ success: false, message: "Only native feedback can be submitted here." });
  const memberId = req.user._id;
  if (doc.preventDuplicate && memberId && doc.responses.some((r) => String(r.member) === String(memberId))) {
    return res.status(409).json({ success: false, message: "You have already submitted this feedback." });
  }
  const answers = req.body.answers || {};
  for (const q of doc.questions) {
    const value = answers[q.id];
    if (q.required && (value === undefined || value === "" || (Array.isArray(value) && !value.length))) {
      return res.status(400).json({ success: false, message: `Please answer: ${q.label}` });
    }
    if (value !== undefined && q.type === "rating" && (Number(value) < 1 || Number(value) > 5)) {
      return res.status(400).json({ success: false, message: `Invalid rating for: ${q.label}` });
    }
    if (value !== undefined && q.type === "single_choice" && q.options.length && !q.options.includes(String(value))) {
      return res.status(400).json({ success: false, message: `Invalid choice for: ${q.label}` });
    }
  }
  const cleanAnswers = {};
  for (const q of doc.questions) {
    if (answers[q.id] !== undefined) cleanAnswers[q.id] = Array.isArray(answers[q.id]) ? answers[q.id].slice(0, 20) : String(answers[q.id]).slice(0, 4000);
  }
  doc.responses.push({ member: doc.anonymous ? null : memberId, anonymous: doc.anonymous, answers: cleanAnswers });
  await doc.save();
  res.status(201).json({ success: true, message: "Thank you for your feedback." });
};

exports.ensureBuiltIn = async (req, res) => {
  const title = "Benovelent Website Experience Check-in";
  const existing = await FeedbackCollection.findOne({ title });
  if (existing) return res.json({ success: true, collection: visible(existing), existing: true });
  const doc = await FeedbackCollection.create({
    title,
    description: "A short member check-in to help the administration improve the portal. This request is clearly labelled and does not silently collect responses.",
    kind: "native",
    questions: normalizeQuestions([
      { id: "experience", type: "rating", label: "How would you rate your overall website experience?", required: true },
      { id: "feature", type: "long_text", label: "What feature would you like us to add or improve next?", required: true },
      { id: "friction", type: "long_text", label: "What part of using the website is confusing or frustrating?", required: false },
      { id: "positive", type: "long_text", label: "What is working well for you and should we keep?", required: false },
    ]),
    anonymous: false, preventDuplicate: true, status: "active", promptOnLogin: true, requireOnLogin: false,
    promptFrequencyDays: 30, autoGenerated: true, createdBy: req.user._id, createdByRole: req.user.role,
  });
  res.status(201).json({ success: true, collection: visible(doc), existing: false });
};

exports.autoGenerate = async (req, res) => {
  const topic = String(req.body?.topic || "member experience").trim().slice(0, 120);
  const templates = [
    { id: "rating", type: "rating", label: `How would you rate your experience with ${topic}?`, required: true },
    { id: "best", type: "long_text", label: `What is working well about ${topic}?`, required: false },
    { id: "improve", type: "long_text", label: `What should we improve next in ${topic}?`, required: true },
    { id: "friction", type: "long_text", label: `What is confusing, slow or frustrating when using ${topic}?`, required: false },
  ];
  res.json({ success: true, autoGenerated: true, questions: normalizeQuestions(templates) });
};

exports.responses = async (req, res) => {
  const doc = await FeedbackCollection.findById(req.params.id).populate("responses.member", "fullName email memberNumber");
  if (!doc) return res.status(404).json({ success: false, message: "Feedback collection not found." });
  res.json({ success: true, collection: visible(doc), responses: doc.responses });
};
