const crypto = require("crypto");
const FeedbackCollection = require("../models/FeedbackCollection");
const Member = require("../models/Member");
const News = require("../models/News");

const ALLOWED_TYPES = new Set(["short_text", "long_text", "email", "number", "rating", "single_choice", "multiple_choice"]);

function normalizeQuestions(questions = []) {
  return (Array.isArray(questions) ? questions : []).map((q) => ({
    id: q.id || crypto.randomUUID(),
    type: ALLOWED_TYPES.has(q.type) ? q.type : "short_text",
    label: String(q.label || "").trim().slice(0, 500),
    required: Boolean(q.required),
    options: Array.isArray(q.options) ? q.options.map((v) => String(v).trim().slice(0, 200)).filter(Boolean).slice(0, 20) : [],
  })).filter((q) => q.label).slice(0, 50);
}

function visible(collection) {
  return {
    _id: collection._id,
    title: collection.title,
    description: collection.description,
    kind: collection.kind,
    googleFormUrl: collection.googleFormUrl,
    questions: collection.questions,
    anonymous: collection.anonymous,
    preventDuplicate: collection.preventDuplicate,
    status: collection.status,
    startDate: collection.startDate,
    endDate: collection.endDate,
    promptOnLogin: Boolean(collection.promptOnLogin),
    requireOnLogin: Boolean(collection.requireOnLogin),
    promptFrequencyDays: Number(collection.promptFrequencyDays || 7),
    autoGenerated: Boolean(collection.autoGenerated),
    publishedToNews: Boolean(collection.publishedToNews),
    publishedNewsId: collection.publishedNewsId || null,
    publishedAt: collection.publishedAt || null,
    createdAt: collection.createdAt,
    responseCount: collection.responses?.length || 0,
  };
}

function validatePromptSettings({ promptOnLogin, requireOnLogin, kind }) {
  if (requireOnLogin && !promptOnLogin) {
    throw new Error("A required login feedback request must also be enabled for login prompts.");
  }
  if (requireOnLogin && kind !== "native") {
    throw new Error("Only native feedback can be required before portal access.");
  }
}

exports.list = async (req, res) => {
  const filter = req.user.role === "member" ? { status: "active" } : {};
  const docs = await FeedbackCollection.find(filter).sort({ createdAt: -1 });
  res.json({ success: true, collections: docs.map(visible) });
};

exports.create = async (req, res) => {
  try {
    const { title, description, kind, googleFormUrl, questions, anonymous, preventDuplicate, status, startDate, endDate, promptOnLogin, requireOnLogin, promptFrequencyDays, autoGenerated } = req.body || {};
    if (!String(title || "").trim() || !["native", "google_form"].includes(kind)) {
      return res.status(400).json({ success: false, message: "Title and a valid feedback type are required." });
    }
    if (kind === "google_form" && !/^https:\/\//i.test(String(googleFormUrl || ""))) {
      return res.status(400).json({ success: false, message: "A secure Google Forms HTTPS URL is required." });
    }
    if (kind === "native" && !Array.isArray(questions)) {
      return res.status(400).json({ success: false, message: "Native feedback questions are required." });
    }
    const normalizedQuestions = kind === "native" ? normalizeQuestions(questions) : [];
    if (Boolean(requireOnLogin) && (!normalizedQuestions.length || !normalizedQuestions.some((question) => question.required))) {
      return res.status(400).json({ success: false, message: "A required login feedback request must contain at least one required question." });
    }
    validatePromptSettings({ promptOnLogin: Boolean(promptOnLogin), requireOnLogin: Boolean(requireOnLogin), kind });
    const doc = await FeedbackCollection.create({
      title: String(title).trim().slice(0, 160), description: String(description || "").trim().slice(0, 2000), kind,
      googleFormUrl: kind === "google_form" ? String(googleFormUrl).trim() : "",
      questions: kind === "native" ? normalizedQuestions : [], anonymous: Boolean(anonymous),
      preventDuplicate: preventDuplicate !== false, status: ["draft", "active", "closed"].includes(status) ? status : "active",
      startDate: startDate || null, endDate: endDate || null,
      promptOnLogin: Boolean(promptOnLogin), requireOnLogin: Boolean(requireOnLogin),
      promptFrequencyDays: Math.max(0, Math.min(3650, Number(promptFrequencyDays ?? 7) || 0)),
      autoGenerated: Boolean(autoGenerated),
      createdBy: req.user._id, createdByRole: req.user.role,
    });
    res.status(201).json({ success: true, collection: visible(doc) });
  } catch (error) {
    res.status(400).json({ success: false, message: error.message });
  }
};

exports.update = async (req, res) => {
  try {
    const doc = await FeedbackCollection.findById(req.params.id);
    if (!doc) return res.status(404).json({ success: false, message: "Feedback collection not found." });
    const allowed = ["title","description","googleFormUrl","questions","anonymous","preventDuplicate","status","startDate","endDate","promptOnLogin","requireOnLogin","promptFrequencyDays","autoGenerated"];
    for (const key of allowed) {
      if (req.body[key] === undefined) continue;
      doc[key] = key === "questions" ? normalizeQuestions(req.body[key]) : req.body[key];
    }
    if (Boolean(doc.requireOnLogin) && (!doc.questions?.length || !doc.questions.some((question) => question.required))) {
      throw new Error("A required login feedback request must contain at least one required question.");
    }
    validatePromptSettings({ promptOnLogin: Boolean(doc.promptOnLogin), requireOnLogin: Boolean(doc.requireOnLogin), kind: doc.kind });
    if (doc.googleFormUrl && doc.kind === "google_form" && !/^https:\/\//i.test(doc.googleFormUrl)) {
      return res.status(400).json({ success: false, message: "Google Forms URL must use HTTPS." });
    }
    await doc.save();
    res.json({ success: true, collection: visible(doc) });
  } catch (error) {
    res.status(400).json({ success: false, message: error.message });
  }
};

exports.remove = async (req, res) => {
  const doc = await FeedbackCollection.findByIdAndDelete(req.params.id);
  if (!doc) return res.status(404).json({ success: false, message: "Feedback collection not found." });
  res.json({ success: true, message: "Feedback collection deleted." });
};

exports.pendingLogin = async (req, res) => {
  const now = new Date();
  const actorId = String(req.user?._id || "");
  const actorRole = String(req.user?.role || "member").toLowerCase();
  const docs = await FeedbackCollection.find({
    kind: "native", status: "active", promptOnLogin: true,
    $and: [{ $or: [{ startDate: null }, { startDate: { $lte: now } }] }, { $or: [{ endDate: null }, { endDate: { $gte: now } }] }],
  }).sort({ requireOnLogin: -1, createdAt: -1 });
  for (const doc of docs) {
    const alreadyAnswered = doc.responses?.some((r) =>
      String(r.member || "") === actorId &&
      (!r.respondentRole || String(r.respondentRole) === actorRole)
    );
    if (alreadyAnswered && doc.preventDuplicate) continue;
    return res.json({ success: true, prompt: visible(doc), required: Boolean(doc.requireOnLogin) });
  }
  return res.json({ success: true, prompt: null, required: false });
};

exports.submit = async (req, res) => {
  const doc = await FeedbackCollection.findById(req.params.id);
  if (!doc || doc.status !== "active") return res.status(404).json({ success: false, message: "Feedback collection is not available." });
  const now = new Date();
  if (doc.startDate && now < doc.startDate) return res.status(400).json({ success: false, message: "Feedback collection has not started yet." });
  if (doc.endDate && now > doc.endDate) return res.status(400).json({ success: false, message: "Feedback collection has closed." });
  if (doc.kind !== "native") return res.status(400).json({ success: false, message: "Only native feedback can be submitted here." });
  const memberId = req.user._id;
  const actorRole = String(req.user?.role || "member").toLowerCase();
  if (doc.preventDuplicate && memberId && doc.responses.some((r) => String(r.member) === String(memberId) && (!r.respondentRole || String(r.respondentRole) === actorRole))) {
    return res.status(409).json({ success: false, message: "You have already submitted this feedback." });
  }
  const answers = req.body.answers || {};
  for (const q of doc.questions) {
    const value = answers[q.id];
    if (q.required && (value === undefined || value === "" || (Array.isArray(value) && !value.length))) {
      return res.status(400).json({ success: false, message: `Please answer: ${q.label}` });
    }
    if (value !== undefined && q.type === "rating" && (Number(value) < 1 || Number(value) > 5)) {
      return res.status(400).json({ success: false, message: `Invalid rating for: ${q.label}` });
    }
    if (value !== undefined && q.type === "single_choice" && q.options.length && !q.options.includes(String(value))) {
      return res.status(400).json({ success: false, message: `Invalid choice for: ${q.label}` });
    }
    if (value !== undefined && q.type === "multiple_choice" && q.options.length) {
      if (!Array.isArray(value) || value.some((option) => !q.options.includes(String(option)))) {
        return res.status(400).json({ success: false, message: `Invalid choices for: ${q.label}` });
      }
    }
  }
  const cleanAnswers = {};
  for (const q of doc.questions) {
    if (answers[q.id] !== undefined) cleanAnswers[q.id] = Array.isArray(answers[q.id]) ? answers[q.id].slice(0, 20) : String(answers[q.id]).slice(0, 4000);
  }
  doc.responses.push({
    member: memberId,
    respondentRole: actorRole,
    anonymous: doc.anonymous,
    answers: cleanAnswers,
  });
  await doc.save();
  res.status(201).json({ success: true, message: "Thank you for your feedback." });
};

exports.ensureBuiltIn = async (req, res) => {
  const title = "Benevolent Website Experience Check-in";
  const existing = await FeedbackCollection.findOne({
    $or: [{ title }, { title: "Benovelent Website Experience Check-in" }],
  });
  if (existing && existing.title !== title) {
    existing.title = title;
    await existing.save();
  }
  if (existing) return res.json({ success: true, collection: visible(existing), existing: true });
  const doc = await FeedbackCollection.create({
    title,
    description: "A short portal check-in to help the administration improve the website. This request is clearly labelled and does not silently collect responses.",
    kind: "native",
    questions: normalizeQuestions([
      { id: "experience", type: "rating", label: "How would you rate your overall website experience?", required: true },
      { id: "feature", type: "long_text", label: "What feature would you like us to add or improve next?", required: true },
      { id: "friction", type: "long_text", label: "What part of using the website is confusing or frustrating?", required: false },
      { id: "positive", type: "long_text", label: "What is working well for you and should we keep?", required: false },
    ]),
    anonymous: false, preventDuplicate: true, status: "active", promptOnLogin: true, requireOnLogin: false,
    promptFrequencyDays: 30, autoGenerated: true, createdBy: req.user._id, createdByRole: req.user.role,
  });
  res.status(201).json({ success: true, collection: visible(doc), existing: false });
};

exports.autoGenerate = async (req, res) => {
  const topic = String(req.body?.topic || "member experience").trim().slice(0, 120);
  const templates = [
    { id: "rating", type: "rating", label: `How would you rate your experience with ${topic}?`, required: true },
    { id: "best", type: "long_text", label: `What is working well about ${topic}?`, required: false },
    { id: "improve", type: "long_text", label: `What should we improve next in ${topic}?`, required: true },
    { id: "friction", type: "long_text", label: `What is confusing, slow or frustrating when using ${topic}?`, required: false },
  ];
  res.json({ success: true, autoGenerated: true, questions: normalizeQuestions(templates) });
};

exports.responses = async (req, res) => {
  const doc = await FeedbackCollection.findById(req.params.id).populate("responses.member", "fullName email memberNumber");
  if (!doc) return res.status(404).json({ success: false, message: "Feedback collection not found." });
  const responses = (doc.responses || []).map((response) => {
    const item = response.toObject ? response.toObject() : { ...response };
    if (item.anonymous) item.member = null;
    return item;
  });
  res.json({ success: true, collection: visible(doc), responses });
};

function csvEscape(value) {
  const text = value == null ? "" : String(value);
  return /[",\n\r]/.test(text) ? `"${text.replace(/"/g, '""')}"` : text;
}

function buildFeedbackCsv(doc) {
  const columns = ["submittedAt", "respondentRole", "memberNumber", "memberName", "memberEmail", ...doc.questions.map((q) => `q:${q.id}`)];
  const rows = [columns.map(csvEscape).join(",")];
  for (const r of doc.responses || []) {
    const member = r.member && typeof r.member === "object" ? r.member : null;
    const values = [
      r.submittedAt ? new Date(r.submittedAt).toISOString() : "",
      r.respondentRole || "member",
      r.anonymous ? "" : (member?.memberNumber || ""),
      r.anonymous ? "" : (member?.fullName || ""),
      r.anonymous ? "" : (member?.email || ""),
      ...doc.questions.map((q) => {
        const value = r.answers?.[q.id];
        return Array.isArray(value) ? value.join(" | ") : (value ?? "");
      }),
    ];
    rows.push(values.map(csvEscape).join(","));
  }
  return rows.join("\n");
}

function parseCsvLine(line) {
  const result = [];
  let current = "";
  let quoted = false;
  for (let i = 0; i < line.length; i += 1) {
    const ch = line[i];
    if (ch === '"' && quoted && line[i + 1] === '"') { current += '"'; i += 1; continue; }
    if (ch === '"') { quoted = !quoted; continue; }
    if (ch === ',' && !quoted) { result.push(current); current = ""; continue; }
    current += ch;
  }
  result.push(current);
  return result;
}

function parseCsv(text) {
  const lines = String(text || "").replace(/^\uFEFF/, "").split(/\r?\n/).filter((line) => line.trim() !== "");
  if (!lines.length) return [];
  const headers = parseCsvLine(lines[0]);
  return lines.slice(1).map((line) => {
    const values = parseCsvLine(line);
    return Object.fromEntries(headers.map((header, i) => [header, values[i] ?? ""]));
  });
}

async function normalizeImportedResponses(doc, rows) {
  const memberCache = new Map();
  const responses = [];
  for (const row of rows.slice(0, 10000)) {
    const memberNumber = String(row.memberNumber || "").trim();
    const email = String(row.memberEmail || row.email || "").trim().toLowerCase();
    let member = null;
    if (memberNumber || email) {
      const cacheKey = `${memberNumber}|${email}`;
      if (memberCache.has(cacheKey)) member = memberCache.get(cacheKey);
      else {
        member = memberNumber
          ? await Member.findOne({ memberNumber }).select("_id fullName email memberNumber")
          : await Member.findOne({ email }).select("_id fullName email memberNumber");
        memberCache.set(cacheKey, member);
      }
    }
    const answers = {};
    for (const q of doc.questions) {
      const raw = row[`q:${q.id}`] ?? row[q.id];
      if (raw === undefined || raw === "") continue;
      answers[q.id] = q.type === "multiple_choice" ? String(raw).split("|").map((v) => v.trim()).filter(Boolean).slice(0, 20) : String(raw).slice(0, 4000);
    }
    if (!Object.keys(answers).length) continue;
    responses.push({
      member: member?._id || null,
      respondentRole: ["member", "admin", "superadmin"].includes(String(row.respondentRole)) ? String(row.respondentRole) : "member",
      anonymous: !member && !memberNumber && !email,
      answers,
      submittedAt: row.submittedAt ? new Date(row.submittedAt) : new Date(),
    });
  }
  return responses;
}

exports.exportResponses = async (req, res) => {
  const doc = await FeedbackCollection.findById(req.params.id).populate("responses.member", "fullName email memberNumber");
  if (!doc) return res.status(404).json({ success: false, message: "Feedback collection not found." });
  const format = String(req.query.format || "csv").toLowerCase();
  const filename = `feedback-${String(doc.title).replace(/[^a-z0-9]+/gi, "-").replace(/^-|-$/g, "").toLowerCase() || "responses"}`;
  if (format === "json") {
    res.setHeader("Content-Disposition", `attachment; filename="${filename}.json"`);
    return res.json({ title: doc.title, exportedAt: new Date().toISOString(), questions: doc.questions, responses: doc.responses });
  }
  res.setHeader("Content-Type", "text/csv; charset=utf-8");
  res.setHeader("Content-Disposition", `attachment; filename="${filename}.csv"`);
  return res.send(buildFeedbackCsv(doc));
};

exports.importResponses = async (req, res) => {
  try {
    const doc = await FeedbackCollection.findById(req.params.id);
    if (!doc) return res.status(404).json({ success: false, message: "Feedback collection not found." });
    if (!req.file) return res.status(400).json({ success: false, message: "Upload a CSV or JSON response file." });
    const raw = req.file.buffer.toString("utf8");
    let payload;
    if (/\.json$/i.test(req.file.originalname) || String(req.file.mimetype).includes("json")) payload = JSON.parse(raw);
    else payload = parseCsv(raw);
    const rows = Array.isArray(payload) ? payload : Array.isArray(payload?.responses) ? payload.responses : [];
    if (!rows.length) return res.status(400).json({ success: false, message: "No response rows were found in the uploaded file." });
    const imported = await normalizeImportedResponses(doc, rows);
    if (!imported.length) return res.status(400).json({ success: false, message: "No usable answers were found for this feedback collection." });
    const mode = String(req.body?.mode || "append").toLowerCase();
    if (mode === "replace") doc.responses = imported;
    else doc.responses.push(...imported);
    await doc.save();
    return res.json({ success: true, imported: imported.length, responseCount: doc.responses.length, collection: visible(doc) });
  } catch (error) {
    return res.status(400).json({ success: false, message: error.message || "Could not import responses." });
  }
};

exports.publishToNews = async (req, res) => {
  const doc = await FeedbackCollection.findById(req.params.id).populate("responses.member", "fullName email memberNumber");
  if (!doc) return res.status(404).json({ success: false, message: "Feedback collection not found." });
  const responseCount = doc.responses?.length || 0;
  const title = `Feedback Report: ${doc.title}`;
  const summary = `${responseCount} response${responseCount === 1 ? "" : "s"} collected.`;
  const questionSummary = doc.questions.map((q) => {
    const values = (doc.responses || []).map((r) => r.answers?.[q.id]).filter((v) => v !== undefined && v !== "");
    if (!values.length) return `${q.label}\nNo responses.`;
    const printable = values.slice(0, 50).map((v) => Array.isArray(v) ? v.join(", ") : String(v)).join("\n• ");
    return `${q.label}\n• ${printable}`;
  }).join("\n\n");
  const content = `${summary}\n\nThis report was published by an authorised ${req.user.role === "superadmin" ? "SuperAdmin" : "Admin"} account.\n\nResponse summary\n\n${questionSummary || "No response data."}\n\nMembers can sign in to download the full response file or print this report.`;
  if (doc.publishedNewsId) {
    const existing = await News.findById(doc.publishedNewsId);
    if (existing) {
      existing.title = title;
      existing.summary = summary;
      existing.content = content;
      existing.published = true;
      existing.status = "published";
      existing.publishDate = new Date();
      existing.featured = false;
      existing.pinned = false;
      existing.feedbackReportId = doc._id;
      await existing.save();
      doc.publishedToNews = true; doc.publishedAt = new Date(); await doc.save();
      return res.json({ success: true, news: existing, collection: visible(doc), updated: true });
    }
  }
  const slug = `${title}-${Date.now()}`.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
  const news = await News.create({
    title, slug, summary, content, category: "General", published: true, status: "published", publishDate: new Date(), author: req.user._id, feedbackReportId: doc._id,
  });
  doc.publishedToNews = true; doc.publishedNewsId = news._id; doc.publishedAt = new Date(); await doc.save();
  return res.json({ success: true, news, collection: visible(doc), updated: false });
};

exports.memberDownload = async (req, res) => {
  const doc = await FeedbackCollection.findOne({ _id: req.params.id, publishedToNews: true }).populate("responses.member", "fullName email memberNumber");
  if (!doc) return res.status(404).json({ success: false, message: "Published feedback report not found." });
  const format = String(req.query.format || "csv").toLowerCase();
  const safe = String(doc.title).replace(/[^a-z0-9]+/gi, "-").replace(/^-|-$/g, "").toLowerCase() || "feedback-report";
  if (format === "json") {
    res.setHeader("Content-Disposition", `attachment; filename="${safe}.json"`);
    return res.json({ title: doc.title, exportedAt: new Date().toISOString(), questions: doc.questions, responses: doc.responses });
  }
  res.setHeader("Content-Type", "text/csv; charset=utf-8");
  res.setHeader("Content-Disposition", `attachment; filename="${safe}.csv"`);
  return res.send(buildFeedbackCsv(doc));
};

