const express = require("express");
const router = express.Router();
const { verifyToken } = require("../middleware/authMiddleware");
const { isAdminOrSuperAdmin } = require("../middleware/roleMiddleware");
const controller = require("../controllers/claimWorkflowController");
const verified = require("../middleware/verifiedMiddleware");
const memberStatus = require("../middleware/memberStatusMiddleware");
const profileCompleted = require("../middleware/profileCompletionMiddleware");
router.get("/statuses", verifyToken, isAdminOrSuperAdmin, controller.statuses);
router.get("/", verifyToken, isAdminOrSuperAdmin, controller.list);
router.get("/:type/:id", verifyToken, isAdminOrSuperAdmin, controller.getOne);
router.put("/:type/:id/stage", verifyToken, isAdminOrSuperAdmin, controller.updateStage);
router.delete("/:type/:id/permanent", verifyToken, isSuperAdmin, controller.permanentDelete);
router.delete("/:type/:id", verifyToken, isAdminOrSuperAdmin, controller.remove);
router.post("/:type/:id/publish-news", verifyToken, isAdminOrSuperAdmin, controller.publishClaimToNews);
router.post("/community/:id/publish-news", verifyToken, isAdminOrSuperAdmin, controller.publishCommunityToNews);
router.post("/community/request", verifyToken, verified, memberStatus, profileCompleted, require("../middleware/roleMiddleware").isMember, controller.requestCommunityAssistance);
router.post("/community/:id/review", verifyToken, isAdminOrSuperAdmin, controller.reviewCommunityAssistance);
module.exports = router;
