const express = require("express");
const router = express.Router();
const { createNews, getNews, getSingleNews, getLatestNews, updateNews, deleteNews, likeNews, unlikeNews, addComment, deleteComment, pinNews, unpinNews } = require("../controllers/newsController");
const { verifyToken: protect } = require("../middleware/authMiddleware");
const { isAdminOrSuperAdmin } = require("../middleware/roleMiddleware");
const { setUploadType, uploadFields } = require("../middleware/upload");

router.post("/", protect, isAdminOrSuperAdmin, setUploadType("news"), uploadFields([{ name: "coverImage", maxCount: 1 }, { name: "images", maxCount: 10 }, { name: "attachments", maxCount: 10 }]), createNews);
router.get("/public", getLatestNews);
router.get("/", protect, getNews);
router.get("/:id", protect, getSingleNews);
router.put("/:id", protect, isAdminOrSuperAdmin, updateNews);
router.delete("/:id", protect, isAdminOrSuperAdmin, deleteNews);
router.put("/:id/like", protect, likeNews);
router.put("/:id/unlike", protect, unlikeNews);
router.post("/:id/comment", protect, addComment);
router.delete("/:id/comment/:commentId", protect, deleteComment);
router.put("/:id/pin", protect, isAdminOrSuperAdmin, pinNews);
router.put("/:id/unpin", protect, isAdminOrSuperAdmin, unpinNews);
module.exports = router;
