'use strict';
const { ROOT, read, assert, pass } = require('./testUtils');

const roleMiddleware = read('backend/middleware/roleMiddleware.js');
const chatProfile = read('backend/utils/chatProfile.js');
const conversationController = read('backend/controllers/conversationController.js');
const conversationRoutes = read('backend/routes/conversationRoutes.js');
const messageController = read('backend/controllers/messageController.js');
const messageRoutes = read('backend/routes/messageRoutes.js');
const messageSocket = read('backend/sockets/messageSocket.js');
const socket = read('backend/sockets/socket.js');
const presence = read('backend/sockets/presence.js');
const memberController = read('backend/controllers/memberController.js');
const memberMessages = read('src/pages/member/Messages.jsx');
const adminMessages = read('src/pages/admin/AdminMessages.jsx');
const center = read('src/components/chat/MessageCenterPage.jsx');
const globalCenter = read('src/components/GlobalCommunicationCenter.jsx');
const bubble = read('src/components/chat/MessageBubble.jsx');
const input = read('src/components/chat/MessageInput.jsx');
const callOverlay = read('src/components/chat/CallOverlay.jsx');
const chatWindow = read('src/components/chat/ChatWindow.jsx');
const support = read('src/pages/member/Support.jsx');
const pendingCallStore = read('src/utils/pushCallStore.js');
const serviceWorker = read('public/sw.js');

assert(/isChatUser\s*=\s*authorize\("member",\s*"admin"\)/.test(roleMiddleware), 'chat routes exclude SuperAdmin');
assert(/CHAT_ROLES\s*=\s*new Set\(\[['"]member['"],\s*['"]admin['"]\]\)/.test(chatProfile), 'canonical chat roles are member/admin only');
assert(/canonicalMe === canonicalTarget/.test(conversationController), 'API blocks self-chat');
assert(/if \(conversation\)[\s\S]*?conversation\.save\(\);[\s\S]*?conversation\.populate\(\s*\"participants\"[\s\S]*?conversation\.populate\(\"lastMessage\"\)/.test(conversationController), 'reused direct conversations return hydrated participants and lastMessage');
assert(/!currentActor \|\| !isChatRole\(currentActor\.role\).*!targetActor \|\| !isChatRole\(targetActor\.role\)/s.test(conversationController), 'API rejects SuperAdmin chat participants');
assert(/isGroup: false/.test(conversationController) && /isGroup: false/.test(messageController), 'chat center is direct 1-to-1 only');
assert(/async function getAuthorizedDirectConversation[\s\S]*participants.*\$size: 2[\s\S]*active: true/.test(conversationController) && /deleteConversation[\s\S]*getAuthorizedDirectConversation\(req.params.id, actorId\)/.test(conversationController) && /archiveConversation[\s\S]*getAuthorizedDirectConversation\(req.params.id, actorId\)/.test(conversationController), 'conversation read/delete/archive operations reject legacy group-shaped records through the shared helper');
assert(/router\.put\("\/:id\/archive"/.test(conversationRoutes), 'archive API exists');
assert(/archivedBy/.test(conversationController) && /pinnedBy/.test(conversationController) && /mutedBy/.test(conversationController), 'viewer-specific conversation state is actor-scoped');
assert(/participants: actorId/.test(messageController), 'message access requires conversation membership');
assert(/clientMessageId/.test(messageController) && /11000/.test(messageController), 'message send has idempotency retry handling');
assert(/reply target.*conversationId/s.test(messageController), 'reply target is constrained to the same conversation');
assert(/forwardMessage/.test(messageController) && /sourceConversation/.test(messageController) && /targetConversation/.test(messageController), 'forward requires source and target authorization');
assert(/if\(String\(msg\.sender\)!==String\(actorId\)\)/.test(messageController), 'edit/delete-for-everyone enforce original sender ownership');
assert(/Only active text messages can be edited/.test(messageController), 'edit is limited to eligible text messages');
assert(/msg\.deletedFor\.includes\(actorId\)/.test(messageController), 'delete-for-me is actor-specific');
assert(/unreactToMessage/.test(messageController) && /router\.delete\("\/:id\/react"/.test(messageRoutes), 'unreact exists');
assert(/searchConversationMessages[\s\S]*getAuthorizedDirectConversation\(conversationId, actorId\)/.test(messageController), 'message search is conversation-authorized through the shared helper');
assert(/router\.get\("\/conversation\/:conversationId\/search"/.test(messageRoutes), 'message-search route exists');
assert(/router\.post\("\/:id\/forward"/.test(messageRoutes), 'forward route exists');
assert(/if \(!isChatRole\(socket\.data\?\.role\)/.test(messageSocket) || /isChatRole\(socket\.data\?\.role\)/.test(messageSocket), 'socket actions derive role from authenticated socket');
assert(/getAuthorizedConversation\(socket, conversationId\)/.test(messageSocket), 'typing/call conversation actions verify socket membership');
assert(/String\(recipient\?\.chatId \|\| ""\) === String\(caller\?\.chatId \|\| ""\)/.test(messageSocket), 'socket calls block self-call');
assert(/recipientSockets.*incoming-call/s.test(messageSocket), 'incoming calls are delivered only to intended recipient sockets');
assert(/reason === "declined".*recordCallSummary\(call, "declined"/s.test(messageSocket), 'declined calls are distinct from missed calls');
assert(/CALL_TIMEOUT_MS.*markMissedCall/s.test(messageSocket), 'call timeout records missed behavior');
assert(/socket\.on\(\"disconnect\"[\s\S]*scheduleCallSignalingRecovery\(current|scheduleCallSignalingRecovery\(current/.test(messageSocket), 'active calls enter a recoverable signaling grace period on socket disconnect');
const callStartedIndex = messageSocket.indexOf('emit("call-started"');
const callNotificationIndex = messageSocket.indexOf('const notification = await deliverCallNotification', callStartedIndex);
assert(callStartedIndex >= 0 && callNotificationIndex > callStartedIndex, 'caller receives the server call id before notification work can delay early ICE tagging');
assert(/resolveCanonicalChatActorForAuthenticatedUser/.test(socket) && /jwt\.verify/.test(socket), 'socket identity is authenticated server-side');
assert(/presence-heartbeat/.test(presence) && /socket\.data\?\.chatId/.test(presence), 'presence derives from authenticated chat identity and heartbeat');
assert(/MessageCenterPage/.test(memberMessages) && /MessageCenterPage/.test(adminMessages), 'Member/Admin use the shared MessageCenter');
assert(!memberMessages.includes('/superadmin/messages') && !adminMessages.includes('/superadmin/messages'), 'no SuperAdmin chat route is exposed');
assert(/onReply/.test(bubble) && /onEdit/.test(bubble) && /onDeleteForEveryone/.test(bubble) && /onForward/.test(bubble), 'message action UX is wired');
assert(/onEdit/.test(input) && /replyTo/.test(input), 'composer supports edit/reply context');
assert(/delivered-message/.test(messageSocket) && /message-delivered/.test(messageSocket), 'delivered state has an authenticated socket acknowledgement');
assert(/onRetry/.test(bubble) && /retryMessage/.test(chatWindow) && /chat-date-separator/.test(chatWindow), 'failed-message retry and date-separator UI are wired');
assert(support.includes('\n              )}\n\n              <Field label="Requested Amount (KES)">'), 'member Support conditional JSX is explicitly closed before Requested Amount');
assert(/getPendingCall/.test(globalCenter) && /removePendingCall/.test(globalCenter) && /incomingPushCall/.test(globalCenter), 'PWA pending call data is consumed by the application-level communication layer');
assert(/eventId: `message:/.test(messageController) && /insertMany/.test(messageController), 'message notifications use an idempotent event identity');
assert(/async function getAuthorizedDirectConversation/.test(messageController) && /isGroup: false/.test(messageController) && /participants\.length !== 2/.test(messageController), 'message operations enforce active direct 1-to-1 authorization');
assert(/new Set\(\["text", "image", "video", "audio", "document"\]\)/.test(messageController) && !/allowedTypes = new Set\(\["text".*"call"/.test(messageController), 'ordinary message API cannot fabricate call messages');
assert(/portalSenderIdentity/.test(messageController) && /sender,\s*senderModel/.test(messageController), 'notification sender identity matches the authenticated portal account');
assert(/conversation-updated/.test(messageController) && /conversation-updated/.test(center), 'unselected conversations receive realtime sidebar updates');
assert(/status: "active"/.test(memberController) && /profile\.toObject/.test(memberController) === false, 'chat directory is active-only by default and does not expose raw admin mirror documents');
assert(/role === 'admin'[\s\S]*ensureChatProfile\(owner\)/.test(chatProfile), 'Admin chat identity resolution uses the existing authenticated portal-owner mirror mechanism');
assert(/member\.memberNumber/.test(read('src/components/chat/ChatSidebar.jsx')) && /member\.phone/.test(read('src/components/chat/ChatSidebar.jsx')), 'directory search covers member number and phone');
assert(/aPinned.*bPinned/s.test(read('src/components/chat/ChatSidebar.jsx')), 'pinned conversations are ordered before unpinned conversations');
assert(/recordSeconds/.test(input) && /recordingTimerRef/.test(input), 'voice-note recording exposes a live timer with cleanup');
assert(/cleanupMedia\(\)/.test(callOverlay) && /ringtoneRef\.current\?\.stop\?\./.test(callOverlay), 'call overlay unmount cleanup releases media and ringtone resources');
assert(/onClose=\{closeActiveCall/.test(globalCenter) && /removePendingCall\(pendingId\)/.test(globalCenter), 'pending PWA call storage is retained until the global communication layer consumes/closes the call');
assert(/notificationclick/.test(serviceWorker) && !/notificationclick[\s\S]*removePendingCall\(callIdValue\)/.test(serviceWorker), 'service worker does not delete pending call data before chat-center consumption');
assert(/const ok = await loadChatData\(\);\s*if \(ok\) toast\.success/.test(center), 'refresh only reports success after chat reload succeeds');

pass('1-to-1 messaging center regression contract (A-AE source controls) passed');
