'use strict';
const { ROOT, read, assert, pass } = require('./testUtils');

const roleMiddleware = read('backend/middleware/roleMiddleware.js');
const chatProfile = read('backend/utils/chatProfile.js');
const conversationController = read('backend/controllers/conversationController.js');
const conversationRoutes = read('backend/routes/conversationRoutes.js');
const messageController = read('backend/controllers/messageController.js');
const messageRoutes = read('backend/routes/messageRoutes.js');
const messageSocket = read('backend/sockets/messageSocket.js');
const socket = read('backend/sockets/socket.js');
const presence = read('backend/sockets/presence.js');
const memberController = read('backend/controllers/memberController.js');
const memberMessages = read('src/pages/member/Messages.jsx');
const adminMessages = read('src/pages/admin/AdminMessages.jsx');
const center = read('src/components/chat/MessageCenterPage.jsx');
const bubble = read('src/components/chat/MessageBubble.jsx');
const input = read('src/components/chat/MessageInput.jsx');
const chatWindow = read('src/components/chat/ChatWindow.jsx');
const support = read('src/pages/member/Support.jsx');
const pendingCallStore = read('src/utils/pushCallStore.js');

assert(/isChatUser\s*=\s*authorize\("member",\s*"admin"\)/.test(roleMiddleware), 'chat routes exclude SuperAdmin');
assert(/CHAT_ROLES\s*=\s*new Set\(\[['"]member['"],\s*['"]admin['"]\]\)/.test(chatProfile), 'canonical chat roles are member/admin only');
assert(/canonicalMe === canonicalTarget/.test(conversationController), 'API blocks self-chat');
assert(/!currentActor \|\| !isChatRole\(currentActor\.role\).*!targetActor \|\| !isChatRole\(targetActor\.role\)/s.test(conversationController), 'API rejects SuperAdmin chat participants');
assert(/isGroup: false/.test(conversationController) && /isGroup: false/.test(messageController), 'chat center is direct 1-to-1 only');
assert(/router\.put\("\/:id\/archive"/.test(conversationRoutes), 'archive API exists');
assert(/archivedBy/.test(conversationController) && /pinnedBy/.test(conversationController) && /mutedBy/.test(conversationController), 'viewer-specific conversation state is actor-scoped');
assert(/participants: actorId/.test(messageController), 'message access requires conversation membership');
assert(/clientMessageId/.test(messageController) && /11000/.test(messageController), 'message send has idempotency retry handling');
assert(/reply target.*conversationId/s.test(messageController), 'reply target is constrained to the same conversation');
assert(/forwardMessage/.test(messageController) && /sourceConversation/.test(messageController) && /targetConversation/.test(messageController), 'forward requires source and target authorization');
assert(/if\(String\(msg\.sender\)!==String\(actorId\)\)/.test(messageController), 'edit/delete-for-everyone enforce original sender ownership');
assert(/Only active text messages can be edited/.test(messageController), 'edit is limited to eligible text messages');
assert(/msg\.deletedFor\.includes\(actorId\)/.test(messageController), 'delete-for-me is actor-specific');
assert(/unreactToMessage/.test(messageController) && /router\.delete\("\/:id\/react"/.test(messageRoutes), 'unreact exists');
assert(/searchConversationMessages/.test(messageController) && /conversationId.*participants: actorId.*isGroup: false/s.test(messageController), 'message search is conversation-authorized');
assert(/router\.get\("\/conversation\/:conversationId\/search"/.test(messageRoutes), 'message-search route exists');
assert(/router\.post\("\/:id\/forward"/.test(messageRoutes), 'forward route exists');
assert(/if \(!isChatRole\(socket\.data\?\.role\)/.test(messageSocket) || /isChatRole\(socket\.data\?\.role\)/.test(messageSocket), 'socket actions derive role from authenticated socket');
assert(/getAuthorizedConversation\(socket, conversationId\)/.test(messageSocket), 'typing/call conversation actions verify socket membership');
assert(/String\(recipient\?\.chatId \|\| ""\) === String\(caller\?\.chatId \|\| ""\)/.test(messageSocket), 'socket calls block self-call');
assert(/recipientSockets.*incoming-call/s.test(messageSocket), 'incoming calls are delivered only to intended recipient sockets');
assert(/reason === "declined".*recordCallSummary\(call, "declined"/s.test(messageSocket), 'declined calls are distinct from missed calls');
assert(/CALL_TIMEOUT_MS.*markMissedCall/s.test(messageSocket), 'call timeout records missed behavior');
assert(/resolveCanonicalChatActorForAuthenticatedUser/.test(socket) && /jwt\.verify/.test(socket), 'socket identity is authenticated server-side');
assert(/presence-heartbeat/.test(presence) && /socket\.data\?\.chatId/.test(presence), 'presence derives from authenticated chat identity and heartbeat');
assert(/MessageCenterPage/.test(memberMessages) && /MessageCenterPage/.test(adminMessages), 'Member/Admin use the shared MessageCenter');
assert(!memberMessages.includes('/superadmin/messages') && !adminMessages.includes('/superadmin/messages'), 'no SuperAdmin chat route is exposed');
assert(/onReply/.test(bubble) && /onEdit/.test(bubble) && /onDeleteForEveryone/.test(bubble) && /onForward/.test(bubble), 'message action UX is wired');
assert(/onEdit/.test(input) && /replyTo/.test(input), 'composer supports edit/reply context');
assert(/delivered-message/.test(messageSocket) && /message-delivered/.test(messageSocket), 'delivered state has an authenticated socket acknowledgement');
assert(/onRetry/.test(bubble) && /retryMessage/.test(chatWindow) && /chat-date-separator/.test(chatWindow), 'failed-message retry and date-separator UI are wired');
assert(support.includes('\n              )}\n\n              <Field label="Requested Amount (KES)">'), 'member Support conditional JSX is explicitly closed before Requested Amount');
assert(/getPendingCall/.test(center) && /removePendingCall/.test(center) && /incomingPushCall/.test(center), 'PWA pending call data is consumed on navigation');
assert(/eventId: `message:/.test(messageController) && /insertMany/.test(messageController), 'message notifications use an idempotent event identity');

pass('1-to-1 messaging center regression contract (A-AE source controls) passed');
