const assert = require("assert");
const fs = require("fs");
const path = require("path");
const ROOT = path.resolve(__dirname, "../..");
const read = (p) => fs.readFileSync(path.join(ROOT, p), "utf8");
const pass = (name) => console.log(`PASS: ${name}`);

const messageController = read("backend/controllers/messageController.js");
const notificationModel = read("backend/models/Notification.js");
const socketServer = read("backend/sockets/socket.js");
const notificationSocket = read("backend/sockets/notificationSocket.js");
const conversationController = read("backend/controllers/conversationController.js");
const topbar = read("src/components/dashboard/DashboardTopbar.jsx");
const notificationCenter = read("src/components/member/NotificationCenter.jsx");
const messageCenter = read("src/components/chat/MessageCenterPage.jsx");
const chatWindow = read("src/components/chat/ChatWindow.jsx");
const chatSound = read("src/utils/chatSound.js");
const callTone = read("src/utils/callTone.js");

assert(!messageController.includes("sendPushToRecipient"), "Message controller must not manually push notifications after Notification.insertMany lifecycle fanout.");
assert(messageController.includes("eventId: `message:${String(newMessage._id)}:"), "Chat notifications must use stable message event IDs.");
assert(!messageController.includes("$inc: { unreadMessages: 1, unreadNotifications: 1 }"), "Legacy member unread counters must not compete with Conversation unreadCounts.");
assert(notificationModel.includes("NotificationModel.getUniqueUnreadCount = getUniqueUnreadCount"), "Notification model must expose the unique unread counter.");
assert(notificationModel.includes("hasActiveUserSocket"), "Live socket presence must gate chat/call push duplication.");
assert(socketServer.includes("hasActiveUserSocket"), "Socket server must expose live-user socket detection.");
assert(notificationSocket.includes("Notification.getUniqueUnreadCount"), "Socket notification-count must use unique unread identity aggregation.");
const notificationController = read("backend/controllers/notificationController.js");
assert(notificationController.includes('emit("notification-deleted"') && notificationController.includes('emit("notifications-cleared"'), "REST notification mutations must synchronize other connected clients.");
assert(conversationController.includes("async function getAuthorizedDirectConversation") && conversationController.includes("{ participants: actorId }") && conversationController.includes("active: true"), "Deleting a conversation must verify participant ownership through the shared active-chat authorization helper.");
assert(conversationController.includes("conversation.pinnedBy = conversation.pinnedBy.filter") && conversationController.includes("conversation.mutedBy = conversation.mutedBy.filter"), "Pin and mute controls must persist both enable and disable actions.");
assert(topbar.includes('socket.on("notification-count"') && !topbar.includes('setUnreadNotifications((v) => Number(v) + 1)'), "Topbar must consume authoritative notification-count events without local +1 drift.");
assert(!topbar.includes('socket.on("message-seen", onMessage)'), "Topbar must not issue a conversations API refresh for each message-seen receipt.");
assert(!notificationCenter.includes("setInterval(load, 30000)"), "Notification center must not poll and refetch every 30 seconds.");
assert(notificationCenter.includes('socket.on("new-notification", onNew)'), "Notification center must reconcile realtime payloads directly.");
const globalCenter = read("src/components/GlobalCommunicationCenter.jsx");
assert(messageCenter.includes("processedMessageIdsRef") && messageCenter.includes("conversationsRef.current"), "Chat sidebar must deduplicate incoming messages before updating conversation previews.");
assert(globalCenter.includes("playIncomingMessageSound") && globalCenter.includes("conversationPrefsRef.current") && globalCenter.includes("new-notification"), "Global communication center must own sound, mute-aware message popups, and realtime notification delivery.");
assert(globalCenter.includes("callAction") && globalCenter.includes("call-rejected"), "Global communication center preserves push-call decline handling.");
assert(messageCenter.includes("sourceMessage = incoming?.message") && messageCenter.includes("incoming?.unreadCount"), "Sidebar message processing normalizes both new-message and conversation-updated payloads without double-counting.");
assert(!chatWindow.includes('API.put(`/messages/${normalized._id}/read`)'), "Active chat must not issue an extra REST read request for every incoming socket message.");
assert(chatWindow.includes("Message sound on") && chatWindow.includes("setChatSoundEnabled"), "Chat details must expose a persisted message-sound control.");
assert(chatSound.includes("catch") && chatSound.includes("benevolentChatSoundEnabled"), "Chat sound must persist preference and safely handle browser audio failures.");
assert(!callTone.includes("setInterval") && !callTone.includes("createOscillator"), "Call ringtone must have a single playback path without duplicate synthetic audio loops.");
pass("Chat notification reliability contract");
