'use strict';
const { read, assert, pass } = require('./testUtils');
const controller = read('backend/controllers/dependentController.js');
const routes = read('backend/routes/dependentRoutes.js');
assert(/DEPENDENT_EDIT_REQUEST_REQUIRED/.test(controller), 'member direct dependent edits must return request-required response');
assert(/DEPENDENT_DELETE_FORBIDDEN/.test(controller), 'member direct dependent deletion must be blocked');
assert(/createEditRequest/.test(controller) && /reviewEditRequest/.test(controller) && /completeEditRequest/.test(controller), 'edit request review and completion workflow must exist');
assert(/approvedChanges/.test(controller) && /status = \"completed\"/.test(controller), 'approved dependent changes must be scoped and explicitly completed');
assert(/createNotification/.test(controller) && /DependentEditRequest/.test(controller), 'dependent edit requests must create a reference-backed notification');
assert(/POST.*edit-requests|router\.post\("\/edit-requests"/.test(routes), 'member edit request route must exist');
assert(/edit-requests\/:id\/complete/.test(routes), 'member approved-change completion route must exist');
assert(/\/admin\/member\/:memberId/.test(routes), 'admin member-dependent management route must exist');
assert(/documents\/:documentId/.test(routes), 'dependent document management routes must exist');
pass('dependent member/admin permission and workflow contracts verified');
