const fs = require("fs");
const assert = require("assert");

const read = (file) => fs.readFileSync(file, "utf8");
const payment = read("backend/controllers/paymentController.js");
const contribution = read("backend/controllers/contributionController.js");
const finance = read("backend/controllers/financeController.js");
const conversation = read("backend/controllers/conversationController.js");
const chatProfile = read("backend/utils/chatProfile.js");
const conversationModel = read("backend/models/Conversation.js");
const news = read("backend/controllers/newsController.js");
const newsRoutes = read("backend/routes/newsRoutes.js");
const upload = read("backend/config/uploadConfig.js");
const server = read("backend/server.js");
const sanitizer = read("backend/utils/clientSanitizer.js");
const migrationRunner = read("backend/utils/runMigrations.js");
const frontendMemberAccounts = read("src/pages/member/Accounts.jsx");
const frontendAdminAccounts = read("src/pages/admin/AdminAccounts.jsx");

assert(!payment.includes('purpose === "contribution"'), "Personal M-PESA contribution branch remains in payment controller.");
assert(!payment.includes("ensureContributionForPayment"), "Personal contribution payment helper remains.");
assert(payment.includes('"loan_repayment", "support_repayment", "community_assistance"'), "Allowed M-PESA purposes are not restricted.");
assert(contribution.includes('source: "payroll"') && contribution.includes('paymentMethod: "Payroll"'), "Contribution creation is not payroll authoritative.");
assert(finance.includes('PAYROLL_ONLY_CONTRIBUTIONS') && finance.includes('paymentMethod: type === "contribution" ? "Payroll"'), "Finance contribution policy is not payroll-only.");
assert(conversation.includes('directKey') && conversation.includes('[canonicalMe, canonicalTarget].sort().join(":")'), "Direct conversation canonical key is missing.");
assert(conversationModel.includes('direct_conversation_key_unique'), "Unique direct conversation index is missing.");
assert(!conversationModel.includes('directKey: { $type: "string", $ne: "" }'), "MongoDB-incompatible direct conversation partial-index predicate remains.");
assert(chatProfile.includes('resolveCanonicalChatActorForAuthenticatedUser') && chatProfile.includes('resolveChatActor'), "Canonical chat identity service is missing.");
assert(!conversation.includes('redisCache.getJson'), "Conversation lists still use blind TTL caching.");
assert(newsRoutes.includes('/:id/publish') && newsRoutes.includes('/:id/unpublish'), "Protected publication endpoints are not wired.");
assert(news.includes('query.published = true') && news.includes('query.status = "published"'), "Member single-news visibility is not forced to published content.");
assert(upload.includes('throw new Error("Cloudinary is required in production.'), "Production Cloudinary requirement is not fail-fast.");
assert(!server.includes('app.use("/uploads", express.static'), "Protected upload directory is still public.");
assert(!server.includes('app.use("/documents", express.static(documentRoot)'), "Protected document directory is still public.");
assert(sanitizer.includes('"monthlyIncome"') && sanitizer.includes('"password"'), "Client sanitizer does not cover required sensitive fields.");
assert(migrationRunner.includes('007_repair_direct_conversations') && migrationRunner.includes('008_normalize_contribution_source'), "New repair migrations are not registered.");
const directRepairMigration = read("backend/migrations/007_repair_direct_conversations.js");
assert(!directRepairMigration.includes('directKey: { $type: "string", $ne: "" }'), "Migration still uses MongoDB-incompatible $ne partial-index predicate.");
assert(!frontendMemberAccounts.includes('purpose="contribution"'), "Member Accounts still renders personal M-PESA contribution.");
assert(!frontendAdminAccounts.includes('purpose="contribution"') && !frontendAdminAccounts.includes('Your Admin contribution'), "Admin Accounts still renders personal contribution M-PESA.");
console.log("Engineering remediation contract tests: PASS");
