#!/usr/bin/env node
const fs=require("fs"),path=require("path"),assert=require("assert");
const root=path.resolve(__dirname,"../.."),read=r=>fs.readFileSync(path.join(root,r),"utf8");
const dashboard=read("src/pages/member/MemberDashboard.jsx"),model=read("backend/models/Notification.js"),nc=read("backend/controllers/notificationController.js"),ns=read("backend/sockets/notificationSocket.js"),ms=read("backend/sockets/messageSocket.js"),top=read("src/components/dashboard/DashboardTopbar.jsx"),payment=read("backend/controllers/paymentController.js"),finance=read("backend/controllers/financeController.js"),fr=read("backend/routes/financeRoutes.js"),sa=read("src/pages/superadmin/SuperAdminAccounts.jsx"),aa=read("src/pages/admin/AdminAccounts.jsx"),pr=read("backend/routes/paymentRoutes.js"),roles=read("backend/middleware/roleMiddleware.js");
assert(!dashboard.includes("/member/accounts?year="),"A: incompatible dashboard Accounts request remains"); assert(dashboard.includes("/member/contributions?year="),"A: member contribution contract missing");
assert(!model.includes('notificationSchema.post("save"'),"B: generic save fanout remains"); assert(!model.includes('notificationSchema.post("findOneAndUpdate"'),"B: generic update fanout remains"); assert(model.includes("fanoutCreatedNotification")&&model.includes("emitNotificationUpdated"),"B: lifecycle split missing"); assert(nc.includes("Notification.emitNotificationUpdated(notification)"),"B: HTTP read update lifecycle missing"); assert(ns.includes("Notification.emitNotificationUpdated(notification)"),"B: socket read update lifecycle missing");
assert(!top.includes('socket.on("new-call-notification", onNotification);'),"C: call-specific event increments general badge"); assert(ms.includes('emit("new-call-notification", callNotification)'),"C: call-specific UI event removed");
const mt=payment.slice(payment.indexOf("exports.myTransactions"),payment.indexOf("exports.getTransaction",payment.indexOf("exports.myTransactions"))); assert(mt.includes("const paymentMember = await resolvePaymentMember(req);"),"D: request-local payment member missing"); assert(!/\n\s*paymentMember\s*=/.test(mt),"D: undeclared/global payment member assignment remains"); assert(mt.includes("MpesaTransaction.find({ member: paymentMember._id })"),"D: transaction ownership filter missing");
const fg=finance.slice(finance.indexOf("exports.getTransaction"),finance.indexOf("/* =====================================================\n   UPDATE TRANSACTION",finance.indexOf("exports.getTransaction"))); assert(fg.includes('if (role === "member")'),"E: member authorization missing"); assert(fg.includes("member: req.user._id"),"E: member ownership query missing"); assert(fg.includes('return res.status(404).json({ success: false, message: "Transaction not found." })'),"E: non-leaking denial missing"); assert(fg.includes('fullName memberNumber email phone'),"F/G: privileged detail projection removed unexpectedly"); assert(fr.includes('router.get("/:id", protect, getTransaction);'),"E-G: finance single route missing"); assert(finance.includes("SETTLED_FINANCE_PROTECTED"),"Settled finance deletion protection missing");
assert(sa.includes("export default function SuperAdminAccounts"),"H: SuperAdmin page not independently composed"); assert(!sa.includes("import AdminAccounts"),"H: SuperAdmin still wraps AdminAccounts"); assert(!sa.includes("MpesaPaymentButton"),"H: SuperAdmin personal M-PESA button present"); assert(sa.includes("community-assistance/${c._id}/payout"),"H: community payout control missing"); assert(pr.includes('router.post("/community-assistance/:id/payout", protect, isSuperAdmin'),"H: payout backend authorization missing"); assert(pr.includes('router.delete("/transactions/:id", protect, isSuperAdmin'),"H: M-PESA delete backend authorization missing"); assert(aa.includes('MpesaPaymentButton purpose="contribution"'),"I: Admin personal contribution UI missing"); assert(roles.includes('const isContributionUser = authorize("member", "admin", "superadmin");'),"I: contribution role middleware missing");
assert(ms.includes('if (String(recipient?.chatId || "") === String(caller?.chatId || ""))'),"J-L: self-call guard missing"); assert(ms.includes('const isChatRole = (role) => ["member", "admin"].includes'),"J/K: intended call roles missing"); assert(ms.includes("CALL_TIMEOUT_MS")&&ms.includes("markMissedCall"),"J/K: call timeout/missed lifecycle missing"); assert(ms.includes("suppressPush: true"),"C/J: call push duplication guard missing"); assert(payment.includes("idempotencyKey")&&payment.includes("reconcileSuccessfulTransaction"),"M: payment idempotency/reconciliation missing");
console.log("FORENSIC REGRESSION TEST PASSED");
