const fs = require("fs");
const assert = require("assert");
const service = fs.readFileSync("backend/services/mpesaService.js", "utf8");
const controller = fs.readFileSync("backend/controllers/paymentController.js", "utf8");
const model = fs.readFileSync("backend/models/MpesaTransaction.js", "utf8");
assert(service.includes("MPESA_TIMEZONE") && service.includes("Africa/Nairobi"), "Daraja timestamp must use Africa/Nairobi time.");
assert(service.includes('Buffer.from(`${shortcode}${env("MPESA_PASSKEY")}${timestampValue}`)'), "Password must use same shortcode/passkey/timestamp value.");
assert(service.includes('transactionType = env("MPESA_TRANSACTION_TYPE"'), "TransactionType must remain config-driven.");
assert(service.includes('isValidTransactionType'), "Transaction type validation missing.");
assert(controller.includes('getStkCallback(req.body)'), "Callback must parse nested and direct callback forms.");
assert(controller.includes("toResultCode(callback)"), "Callback must preserve provider result code.");
assert(controller.includes('[mpesa][callback:failed]'), "Callback failure must be observable.");
assert(model.includes('callbackProcessingError'), "Callback processing errors must be persisted.");
assert(model.includes('requestId'), "Payment correlation id must be persisted.");
console.log("MPESA PRODUCTION DIAGNOSTICS CONTRACT TEST PASSED");
