const fs=require("fs");
const route=fs.readFileSync("backend/routes/paymentRoutes.js","utf8");
const controller=fs.readFileSync("backend/controllers/paymentController.js","utf8");
const service=fs.readFileSync("backend/services/mpesaService.js","utf8");
const api=fs.readFileSync("src/components/payments/MpesaPaymentButton.jsx","utf8");
const assert=(condition,message)=>{if(!condition)throw new Error(message);};
assert(route.includes('router.post("/stk", protect, isContributionUser, controller.stk);'),"Canonical STK route missing.");
assert(route.includes('router.post("/stk-query", protect, isContributionUser, controller.stkQuery);'),"STK query route missing.");
assert(route.includes('router.post("/stkpush", protect, isMember, controller.stk);'),"STK compatibility alias missing.");
assert(route.includes('router.post("/mpesa-stk", protect, isMember, controller.stk);'),"M-PESA compatibility alias missing.");
assert(service.includes('/mpesa/stkpush/v1/processrequest'),"Daraja STK endpoint missing.");
assert(service.includes('/mpesa/stkpushquery/v1/query'),"Daraja STK query endpoint missing.");
assert(service.includes('/oauth/v1/generate?grant_type=client_credentials'),"Daraja OAuth endpoint missing.");
assert(service.includes("CallBackURL") && service.includes("MPESA_CALLBACK_URL"),"STK callback URL not sent.");
assert(service.includes('BusinessShortCode: shortcode'),"BusinessShortCode payload missing.");
assert(/responseCode\s*!==\s*0/.test(controller) && controller.includes("Safaricom accepted the STK request"),"STK success response check missing.");
assert(controller.includes("upstream.status === 404") || controller.includes("upstreamStatus === 404"),"Provider 404 diagnostics missing.");
assert(api.includes('API.post("/payments/stk"'),"Frontend canonical STK request missing.");
assert(api.includes('API.post("/payments/stk-query"'),"Frontend STK query fallback missing.");
assert(api.includes("status === 404") && api.includes("payment API route is missing"),"Frontend 404 diagnostics missing.");
assert(service.includes('paymentStage: "oauth"') || service.includes('paymentStage = "oauth"'),"OAuth failure stage is not tracked.");
assert(service.includes('paymentStage: "stk_query"'),"STK query failure stage is not tracked.");
assert(controller.includes("paymentStage === \"oauth\""),"Controller does not distinguish OAuth failures from STK failures.");
assert(api.includes("paymentStage === \"oauth\""),"Frontend OAuth failure message handling missing.");
console.log("MPESA STK CONTRACT TEST PASSED");
