'use strict';
const { ROOT, read, walk, assert, pass } = require('./testUtils');
const presence = read('backend/sockets/presence.js');
const messageSocket = read('backend/sockets/messageSocket.js');
const chatProfile = read('backend/utils/chatProfile.js');
const dependentModel = read('backend/models/DependentDocument.js');
const dependentRoutes = read('backend/routes/dependentRoutes.js');
const dependentController = read('backend/controllers/dependentController.js');
const notificationController = read('backend/controllers/notificationController.js');
const finance = read('backend/services/financeLedgerService.js');
const memberMessages = read('src/pages/member/Messages.jsx');
const memberRoutes = read('backend/routes/memberRoutes.js');
const financeController = read('backend/controllers/financeController.js');
const sw = read('public/sw.js');
const superadminDashboard = read('src/pages/superadmin/SuperAdminDashboard.jsx');
const accountsPages = [read('src/pages/member/Accounts.jsx'), read('src/pages/admin/AdminAccounts.jsx'), read('src/pages/superadmin/SuperAdminAccounts.jsx')];
const adminMessages = read('src/pages/admin/AdminMessages.jsx');
const messageCenter = read('src/components/chat/MessageCenterPage.jsx');
const adminSupport = read('src/pages/admin/AdminSupport.jsx');

assert(/socket\.on\(["']user-online/.test(presence) && /socket\.on\(["']presence-heartbeat/.test(presence), 'central presence service owns online/heartbeat events');
assert(/goOnline\(\);/.test(presence), 'presence becomes live immediately after authenticated socket registration');
assert(!/socket\.on\(["']user-online/.test(messageSocket), 'chat socket no longer owns duplicate presence registration');
assert(!/socket\.on\(["']presence-heartbeat/.test(messageSocket), 'chat socket no longer owns duplicate heartbeat registration');
assert(/role === 'superadmin'[\s\S]*chatId: String\(user\._id\)[\s\S]*chatProfile: null/.test(chatProfile), 'SuperAdmin has portal presence identity without a chat mirror');
assert(/dependent-id-front/.test(dependentModel) && /dependent-id-back/.test(dependentModel) && /storageFilename/.test(dependentModel), 'dependent document model accepts front/back ID types and persistent storage filenames');
assert(/router\.put\("\/:id", protect, isAdminOrSuperAdmin/.test(dependentRoutes), 'member direct dependent PUT is route-blocked');
assert(/router\.delete\("\/:id", protect, isAdminOrSuperAdmin/.test(dependentRoutes), 'member direct dependent DELETE is route-blocked');
assert(/downloadUrl/.test(dependentController) && /exports\.getDependentDocumentFile/.test(dependentController), 'dependent document storage URLs are replaced by protected download endpoints');
assert(/Promise\.all\(/.test(memberMessages) && !/Promise\.allSettled/.test(memberMessages), 'member chat loader propagates API failures');
assert(/Promise\.all\(/.test(adminMessages) && !/Promise\.allSettled/.test(adminMessages), 'admin chat loader propagates API failures');
assert(!/setPeople\(\[\]\)[\s\S]*setConversations\(\[\]\)/.test(messageCenter), 'shared chat loader does not convert failures into empty data');
assert(/bookBalance/.test(finance) && /moneyIn/.test(finance) && /moneyOut/.test(finance), 'authoritative finance service exposes live balance metrics');
assert((financeController.match(/memberId: role === "member" \? req\.user\._id : null/g) || []).length >= 5, 'member-accessible ledger endpoints are explicitly member-scoped');
assert(accountsPages.every((page) => /finance\/book-balance/.test(page) && /bookBalance/.test(page)), 'all three Accounts pages load the live book balance independently');
assert(/BROADCAST_IN_PROGRESS/.test(notificationController) && /targetedUsers/.test(notificationController) && /pushSent/.test(notificationController), 'broadcast contract is idempotent and reports delivery channels separately');
assert(/Promise\.all\(/.test(adminSupport) && !/Promise\.allSettled/.test(adminSupport), 'Support & Broadcast page propagates independent load failures');
assert(!/superadmin\/messages/.test(sw) && !/SuperAdminMessages/.test(sw), 'service worker contains no removed SuperAdmin chat deep link');
assert(!/MessageCircle/.test(superadminDashboard), 'SuperAdmin dashboard contains no chat icon reference');
const sourceFiles = [...walk(`${ROOT}/src`, ['.js', '.jsx']), ...walk(`${ROOT}/backend`, ['.js']).filter((file) => !file.includes(`${ROOT}/backend/scripts/`)), ...walk(`${ROOT}/public`, ['.js'])];
const stale = [];
for (const file of sourceFiles) {
  const text = read(file.replace(`${ROOT}/`, ''));
  const removedChatRoute = '/superadmin' + '/messages';
  const removedChatComponent = 'SuperAdmin' + 'Messages';
  if (text.includes(removedChatRoute) || text.includes(removedChatComponent)) stale.push(file.replace(`${ROOT}/`, ''));
}
assert(stale.length === 0, `removed SuperAdmin chat references remain: ${stale.join(', ')}`);
pass('production contract regression checks verified');
