const fs = require('fs');
const path = require('path');
const root = path.join(__dirname, '..', '..');
const read = (file) => fs.readFileSync(path.join(root, file), 'utf8');
const must = (condition, message) => { if (!condition) throw new Error(message); };

const memberController = read('backend/controllers/memberController.js');
const financeRoutes = read('backend/routes/financeRoutes.js');
const financeController = read('backend/controllers/financeController.js');
const supportController = read('backend/controllers/supportRequestController.js');
const supportRoutes = read('backend/routes/supportRequestRoutes.js');
const menu = read('src/config/dashboardMenu.js');
const app = read('src/App.jsx');
const leaders = read('backend/routes/leaderRoutes.js');
const home = read('src/pages/Home.jsx');
const redis = read('backend/services/redisCache.js');
const adminController = read('backend/controllers/adminController.js');
const adminMembers = read('src/pages/admin/AdminMembers.jsx');
const adminService = read('src/services/adminService.js');
const contributionsPage = read('src/pages/member/Contributions.jsx');
const financeUi = read('src/pages/admin/AdminFinance.jsx');
const assistant = read('backend/controllers/platformController.js');
const assistantUi = read('src/components/SmartAssistant.jsx');

must(memberController.includes('const { MEMBER_STATUS } = require("../constants/memberStatus");'), 'MEMBER_STATUS import missing.');
must(memberController.includes('String(member.status || "").toLowerCase() === MEMBER_STATUS.ACTIVE'), 'Eligibility status comparison missing.');
must(financeRoutes.includes('router.delete("/:id", protect, isSuperAdmin, deleteTransaction);'), 'Finance delete route is not SuperAdmin-only.');
must(financeController.includes('Only SuperAdmin can permanently delete a financial transaction'), 'Finance controller defense-in-depth guard missing.');
must(supportController.includes('exports.memberUpdate') && supportController.includes('exports.memberRemove'), 'Member support lifecycle handlers missing.');
must(supportController.includes('At least two supporting documents are required.'), 'Minimum document rule missing.');
must(supportController.includes('documents from at least two different categories'), 'Distinct document category rule missing.');
must(supportRoutes.includes('router.put("/mine/:id"') && supportRoutes.includes('router.delete("/mine/:id"'), 'Member support edit/delete routes missing.');
must(!menu.includes('{ title: "Chat", icon: MessageCircle, path: "/superadmin/messages" }'), 'SuperAdmin Chat remains in navigation.');
must(app.includes('/superadmin/messages') && app.includes('Navigate to="/superadmin"'), 'Legacy SuperAdmin Chat redirect missing.');
must(menu.includes('path: "/superadmin/feedback"'), 'SuperAdmin Feedback missing from navigation.');
must(leaders.includes('router.get("/current"'), 'Current leadership endpoint missing.');
must(leaders.includes('Admin.find') && leaders.includes('SuperAdmin.find'), 'Leadership endpoint does not combine administrator records.');
must(home.includes('/leaders/current') && home.includes('leader-card'), 'Home leadership cards missing.');
must(redis.includes('invalidatePrefix'), 'Redis namespace invalidation missing.');
must(adminController.includes('const siteStation = String(req.query.siteStation || "").trim();'), 'Admin site-station filter backend missing.');
must(adminService.includes('siteStation = ""'), 'Admin site-station filter service missing.');
must(adminMembers.includes('Filter by site station'), 'Admin site-station filter UI missing.');
must(financeRoutes.includes('router.patch("/:id/visibility", protect, isSuperAdmin, hideTransaction);'), 'Finance visibility must remain SuperAdmin-only.');
must(financeController.includes('startDate') && financeController.includes('endDate') && financeController.includes('moneyIn') && financeController.includes('moneyOut'), 'Member account date-range/Money In-Money Out support missing.');
must(financeUi.includes('Permanent deletion is reserved for SuperAdmin'), 'Admin finance must explain deletion boundary.');
must(contributionsPage.includes('Opening date') && contributionsPage.includes('Closing date') && contributionsPage.includes('Money In'), 'Member Accounts date-range and Money In UI missing.');
must(assistant.includes('ASSISTANT_KNOWLEDGE') && assistant.includes('configuredFaqs'), 'Context-aware grounded assistant knowledge missing.');
must(assistantUi.includes('suggested') && assistantUi.includes('path.includes("support")'), 'Page-aware assistant quick suggestions missing.');
console.log('UPGRADE CONTRACT TEST PASSED');
