import { useEffect, useState } from "react";
import { HeartHandshake, RefreshCw, Smartphone } from "lucide-react";
import DashboardLayout from "../../layouts/DashboardLayout";
import API from "../../services/api";
import "../../styles/portalModule.css";

const STAGES=["Pending","Under Review","Documents Required","Eligibility Review","Approval Review","Approved","Disbursement Pending","Paid","Completed","Rejected","Cancelled","Closed"];
const stageCopy={Pending:"Submitted and awaiting assignment.","Under Review":"An administrator is checking the application and documents.","Documents Required":"More or clearer supporting documents are needed.","Eligibility Review":"Eligibility, membership and scheme rules are being checked.","Approval Review":"The case is being considered for final approval.",Approved:"Approved. The next step is processing/disbursement.","Disbursement Pending":"Approval is complete; funds are being prepared.",Paid:"Payment/disbursement has been recorded.",Completed:"The support process is complete.",Rejected:"The request was not approved. Community assistance may be requested.",Cancelled:"This application has been cancelled.",Closed:"This application is closed."};
const money=v=>new Intl.NumberFormat("en-KE",{style:"currency",currency:"KES",maximumFractionDigits:0}).format(Number(v||0));
const fmt=v=>v?new Date(v).toLocaleString("en-KE",{day:"2-digit",month:"short",year:"numeric",hour:"2-digit",minute:"2-digit"}):"—";
export default function Claims(){
 const [claims,setClaims]=useState([]),[campaigns,setCampaigns]=useState([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(""),[error,setError]=useState(""),[success,setSuccess]=useState(""),[target,setTarget]=useState({}),[phone,setPhone]=useState({}),[amount,setAmount]=useState({});
 const load=async()=>{try{setLoading(true);setError("");const [claimsRes,casesRes]=await Promise.all([API.get("/member/claims"),API.get("/payments/community-assistance/mine")]);setClaims(Array.isArray(claimsRes.data?.claims)?claimsRes.data.claims:[]);setCampaigns(Array.isArray(casesRes.data?.campaigns)?casesRes.data.campaigns:[]);}catch(e){setError(e.response?.data?.message||e.message||"Unable to load your claims.");}finally{setLoading(false);}};
 useEffect(()=>{load();},[]);
 const campaignFor=(c)=>campaigns.find(x=>String(x.referenceId)===String(c._id)&&String(x.referenceModel||"").toLowerCase().includes(String(c.sourceType||"").toLowerCase()));
 const requestCommunity=async(c)=>{try{setBusy(`community-${c._id}`);setError("");const t=Number(target[c._id]||c.requestedAmount||c.amount||0);const referenceModel={medical:"MedicalSupport",funeral:"FuneralSupport",education:"EducationSupport",support:"SupportRequest"}[c.sourceType];const {data}=await API.post("/claims/community/request",{referenceModel,referenceId:c._id,targetAmount:t});if(!data?.success)throw new Error(data?.message||"Unable to create community support request.");setSuccess("Community support request created. You can now share it and receive M-PESA contributions.");await load();}catch(e){setError(e.response?.data?.message||e.message||"Unable to create community support request.");}finally{setBusy("");}};
 const contribute=async(c)=>{try{setBusy(`pay-${c._id}`);setError("");const a=Number(amount[c._id]||0);if(a<=0)throw new Error("Enter a contribution amount.");const {data}=await API.post("/payments/stk",{purpose:"community_assistance",referenceId:c._id,amount:a,phoneNumber:phone[c._id]||undefined});if(!data?.success)throw new Error(data?.message||"Unable to start M-PESA payment.");setSuccess(data?.message||"M-PESA payment prompt sent to your phone.");}catch(e){setError(e.response?.data?.message||e.message||"Unable to start M-PESA payment.");}finally{setBusy("");}};
 return <DashboardLayout><div className="portal-module"><header className="portal-module-header"><div><span>MEMBER CLAIMS</span><h1>Claims & Applications</h1><p>Track each review stage, understand the latest decision, and request community assistance after a declined claim.</p></div><button className="portal-btn" onClick={load} disabled={loading}><RefreshCw size={16}/>{loading?"Refreshing…":"Refresh"}</button></header>{error&&<div className="portal-alert">{error}</div>}{success&&<div className="portal-alert success">{success}</div>}
 {loading?<div className="portal-empty">Loading your claims…</div>:claims.length===0?<div className="portal-empty"><h3>No claims yet</h3><p>Submit a support request from Support and it will appear here.</p></div>:<div className="portal-grid two">{claims.map(c=>{const status=c.status||"Pending",idx=STAGES.indexOf(status),history=Array.isArray(c.timeline)?c.timeline:[],campaign=campaignFor(c);return <article className="portal-panel" key={`${c.sourceType}-${c._id}`}><div style={{display:"flex",justifyContent:"space-between",gap:10,alignItems:"start"}}><div><span className="portal-badge">{String(c.supportType||"support").toUpperCase()}</span><h2>{c.description||c.purpose||c.hospitalName||c.deceasedName||"Support application"}</h2><p>Submitted {fmt(c.createdAt||c.applicationDate)}</p></div><span className={`portal-badge ${["Rejected","Cancelled","Closed"].includes(status)?"rejected":["Approved","Paid","Completed"].includes(status)?"approved":""}`}>{status}</span></div>
 <div className="portal-stat-grid"><div className="portal-stat"><span>Requested</span><strong>{money(c.requestedAmount||c.amount)}</strong></div><div className="portal-stat"><span>Approved</span><strong>{money(c.approvedAmount)}</strong></div>{c.repaymentEnabled&&<div className="portal-stat"><span>Repayment balance</span><strong>{money(c.balance)}</strong></div>}</div>
 {idx>=0&&<div style={{marginTop:12}}><strong>Review progress</strong><div style={{display:"grid",gap:8,marginTop:8}}>{STAGES.map((s,i)=><div key={s} style={{display:"grid",gridTemplateColumns:"18px 1fr",gap:8,opacity:i<=idx||status===s?1:.42}}><div style={{width:14,height:14,borderRadius:"50%",background:i<=idx?"#0f766e":"#cbd5e1",marginTop:3}}/><div><strong>{s}</strong><div style={{fontSize:13}}>{stageCopy[s]}</div></div></div>)}</div></div>}
 {status==="Rejected"&&!campaign&&<div className="portal-panel" style={{marginTop:14,background:"#fff7ed",border:"1px solid #fed7aa"}}><div style={{display:"flex",gap:10,alignItems:"start"}}><HeartHandshake size={22}/><div><h3 style={{margin:"0 0 4px"}}>Community support is available</h3><p style={{marginTop:0}}>Because this claim was declined, you may request voluntary community assistance. The approved community request can receive M-PESA contributions from other members.</p></div></div><label style={{display:"grid",gap:6,marginTop:10}}><span>Community target (KES)</span><input type="number" min="1" value={target[c._id]??(c.requestedAmount||c.amount||"")} onChange={e=>setTarget({...target,[c._id]:e.target.value})}/></label><button className="portal-btn" style={{marginTop:10}} onClick={()=>requestCommunity(c)} disabled={busy===`community-${c._id}`}>{busy===`community-${c._id}`?"Creating…":"Request community support"}</button></div>}
 {campaign&&<div className="portal-panel" style={{marginTop:14,background:"#f8fafc"}}><div style={{display:"flex",justifyContent:"space-between",gap:10}}><div><span className="portal-badge">COMMUNITY M-PESA</span><h3 style={{margin:"8px 0 4px"}}>{campaign.title}</h3><p>{campaign.description}</p></div><strong>{money(campaign.raisedAmount)} / {money(campaign.targetAmount)}</strong></div>{["open","target_reached"].includes(campaign.status)&&campaign.status!=="target_reached"&&<div className="portal-form-grid" style={{marginTop:10}}><div className="portal-field"><label>Phone</label><input value={phone[campaign._id]||""} onChange={e=>setPhone({...phone,[campaign._id]:e.target.value})} placeholder="07XXXXXXXX"/></div><div className="portal-field"><label>Contribution</label><input type="number" min="1" value={amount[campaign._id]||""} onChange={e=>setAmount({...amount,[campaign._id]:e.target.value})} placeholder="Amount"/></div></div>}{campaign.status==="open"&&<button className="portal-btn" style={{marginTop:10}} onClick={()=>contribute(campaign)} disabled={busy===`pay-${campaign._id}`}><Smartphone size={16}/>{busy===`pay-${campaign._id}`?"Starting M-PESA…":"Contribute via M-PESA"}</button>}</div>}
 {status==="Rejected"&&<div className="portal-alert" style={{marginTop:12}}><strong>Reason:</strong> {c.rejectionReason||c.remarks||"Your application was declined."}</div>}
 {history.length>0&&<div style={{marginTop:14}}><h3>Review history</h3>{history.slice().reverse().map((h,i)=><div key={`${h.date}-${i}`} style={{padding:"10px 0",borderBottom:"1px solid #e5e7eb"}}><strong>{h.status}</strong><div>{h.remarks||"No additional note."}</div><small>{fmt(h.date)}</small></div>)}</div>}</article>})}</div>}
 </div></DashboardLayout>;
}
