import { confirmAction } from "../../utils/modernDialog";
import { useEffect, useState } from "react";
import { Newspaper, Upload, Trash2, RefreshCw } from "lucide-react";
import toast from "react-hot-toast";
import DashboardLayout from "../../layouts/DashboardLayout";
import { createManagedNews, deleteManagedNews, getManagedNews } from "../../services/newsService";
import "./SuperAdminNews.css";

const initial = { title: "", summary: "", content: "", category: "Announcement", published: true, featured: false, pinned: false };

export default function SuperAdminNews() {
  const [items, setItems] = useState([]); const [form, setForm] = useState(initial); const [cover, setCover] = useState(null); const [images, setImages] = useState(null); const [attachments, setAttachments] = useState(null); const [loading, setLoading] = useState(false);
  const load = async () => { try { setLoading(true); const r = await getManagedNews({ limit: 100 }); setItems(r?.news || []); } catch (e) { toast.error(e.response?.data?.message || "Could not load news."); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const submit = async (e) => { e.preventDefault(); try { setLoading(true); const fd = new FormData(); Object.entries(form).forEach(([k,v]) => fd.append(k, typeof v === "boolean" ? String(v) : v)); if (cover) fd.append("coverImage", cover); Array.from(images || []).forEach(f => fd.append("images", f)); Array.from(attachments || []).forEach(f => fd.append("attachments", f)); const r = await createManagedNews(fd); toast.success("News published."); setItems(prev => [r.news, ...prev]); setForm(initial); setCover(null); setImages(null); setAttachments(null); e.target.reset(); } catch (err) { toast.error(err.response?.data?.message || "Could not publish news."); } finally { setLoading(false); } };
  const remove = async (id) => { if (!await confirmAction("Delete this news item permanently?")) return; try { await deleteManagedNews(id); setItems(prev => prev.filter(item => item._id !== id)); toast.success("News deleted."); } catch (e) { toast.error(e.response?.data?.message || "Could not delete news."); } };
  return <DashboardLayout><main className="superadmin-news-page"><div className="superadmin-news-header"><div><span>LIVE NEWSROOM</span><h1><Newspaper size={28}/> News Management</h1><p>Publish and remove news directly from the live website.</p></div><button type="button" className="btn btn-secondary" onClick={load} disabled={loading}><RefreshCw size={16}/> Refresh</button></div><form className="portal-module superadmin-news-form" onSubmit={submit}><div className="feedback-grid"><label>Title<input type="text" required value={form.title} onChange={e => setForm({...form,title:e.target.value})} placeholder="News title" /></label><label>Category<select value={form.category} onChange={e => setForm({...form,category:e.target.value})}><option value="Announcement">Announcement</option><option value="Event">Event</option><option value="General">General</option></select></label></div><label>Summary<textarea rows="3" value={form.summary} onChange={e => setForm({...form,summary:e.target.value})} /></label><label>Content<textarea rows="8" required value={form.content} onChange={e => setForm({...form,content:e.target.value})} /></label><div className="feedback-grid"><label>Cover image<input type="file" accept="image/*" onChange={e => setCover(e.target.files?.[0] || null)} /></label><label>Gallery images<input type="file" accept="image/*" multiple onChange={e => setImages(e.target.files)} /></label></div><label>Attachments<input type="file" multiple onChange={e => setAttachments(e.target.files)} /></label><div className="news-checks"><label><input type="checkbox" checked={form.featured} onChange={e => setForm({...form,featured:e.target.checked})}/> Featured</label><label><input type="checkbox" checked={form.pinned} onChange={e => setForm({...form,pinned:e.target.checked})}/> Pinned</label></div><button className="btn btn-primary" type="submit" disabled={loading}><Upload size={16}/> {loading ? "Publishing..." : "Publish News"}</button></form><section className="portal-module"><div className="portal-module-header"><div><span>LIVE CONTENT</span><h2>Published & existing news</h2></div></div><div className="managed-news-list">{items.length === 0 ? <div className="portal-empty">No news has been published yet.</div> : items.map(item => <article key={item._id} className="managed-news-item"><div><span>{item.category || "News"}</span><h3>{item.title}</h3><p>{item.summary || item.content}</p><small>{item.createdAt ? new Date(item.createdAt).toLocaleString() : ""}</small></div><button className="icon-btn danger" type="button" title="Delete news" onClick={() => remove(item._id)}><Trash2 size={18}/></button></article>)}</div></section></main></DashboardLayout>;
}
