import { Link } from "react-router-dom";
import { MessageCircle, ShieldCheck, HeartHandshake, Sparkles, Phone, Loader2 } from "lucide-react";
import { useEffect, useState } from "react";
import API from "../services/api";
import "../styles/public-modern.css";
const shouldSkipBackgroundVideo = typeof navigator !== "undefined" && (navigator.connection?.saveData || /2g/.test(navigator.connection?.effectiveType || ""));
const aboutVideo = "/videos/benevolent-community-loop.mp4";

export default function About() {
  const [section,setSection]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState("");
  useEffect(()=>{API.get("/website").then(({data})=>setSection((data?.content||[]).find((item)=>item?.section==="about")||null)).catch(e=>setError(e.response?.data?.message||"Unable to load the published About content.")).finally(()=>setLoading(false));},[]);
  const text=section?.content?.body||section?.content?.text||section?.description||"";
  return <main className="public-modern-page"><section className="modern-hero"><video className="modern-hero-video" autoPlay={!shouldSkipBackgroundVideo} muted loop playsInline preload={shouldSkipBackgroundVideo ? "none":"metadata"} poster="/hero.jpg"><source src={aboutVideo} type="video/mp4" /></video><div className="modern-hero-overlay" /><div className="modern-hero-content"><div><span className="modern-kicker"><Sparkles size={14}/> ABOUT MIDAX & BENOVELENT</span><h1>{loading?<><Loader2 size={18}/> Loading…</>:section?.title||"About Benevolent MIDAX"}</h1><p>{loading?"Loading the current published content…":error||section?.subtitle||section?.description||"The current organisation information has not been configured."}</p><div className="modern-hero-actions"><Link to="/contact" className="modern-btn">Your member voice is needed <MessageCircle size={17}/></Link><Link to="/services" className="modern-btn-secondary">View support services</Link></div></div><div className="modern-hero-panel"><div className="modern-panel-grid"><Link to="/contact" className="modern-metric"><strong>Member voice</strong><span>Use the current Contact channel</span></Link><Link to="/privacy-policy" className="modern-metric"><strong>Privacy</strong><span>Read the published Privacy Policy</span></Link><Link to="/services" className="modern-metric"><strong>Support</strong><span>See current enabled policies</span></Link></div></div></div></section><section className="modern-section"><div className="modern-section-head"><span className="eyebrow">PUBLISHED ABOUT CONTENT</span><h2>{section?.subtitle||"Current organisation and scheme information"}</h2>{error&&<p role="alert">{error}</p>}</div><div className="modern-card"><h3>{section?.title||"About"}</h3><p style={{whiteSpace:"pre-wrap"}}>{loading?"Loading…":text||"Not configured"}</p></div></section><section className="modern-section"><div className="modern-card-grid"><div className="modern-card"><HeartHandshake size={24}/><h3>Representatives</h3><p>The current published WebsiteContent is the source for organisation-specific representation information.</p></div><div className="modern-card"><ShieldCheck size={24}/><h3>Accountability</h3><p>Use the current Constitution and published governance content for authoritative accountability rules.</p></div><div className="modern-card"><Phone size={24}/><h3>Communication</h3><p>Use Contact for the current official communication channels.</p></div></div></section></main>;
}
