import { useState } from "react";
import { Phone, Mail, MessageCircle, MapPin, Send, CheckCircle2, Loader2, ArrowRight, Clock } from "lucide-react";
import API from "../services/api";
import { usePublicSettings } from "../hooks/usePublicSettings";
import "../styles/public-modern.css";
const shouldSkipBackgroundVideo = typeof navigator !== "undefined" && (navigator.connection?.saveData || /2g/.test(navigator.connection?.effectiveType || ""));
const heroVideo = "/videos/benevolent-contact-loop.mp4";
export default function Contact() {
  const {settings,loading,error:settingsError}=usePublicSettings(); const [form,setForm]=useState({fullName:"",email:"",phone:"",subject:"",message:""}); const [status,setStatus]=useState({}); const [busy,setBusy]=useState(false);
  const org=settings?.organization||{}; const socials=org.socialChannels||{}; const onChange=k=>e=>setForm(c=>({...c,[k]:e.target.value}));
  const submit=async e=>{e.preventDefault();setBusy(true);setStatus({});try{const {data}=await API.post("/contact",form);setStatus({type:"success",message:data.message||"Message sent successfully."});setForm({fullName:"",email:"",phone:"",subject:"",message:""});}catch(err){setStatus({type:"error",message:err.response?.data?.message||"Unable to send your message."});}finally{setBusy(false);}};
  const items=[[Phone,"Phone",org.phone||"Not configured",org.phone?`tel:${org.phone}`:null],[Mail,"Email",org.email||"Not configured",org.email?`mailto:${org.email}`:null],[MessageCircle,"WhatsApp",socials.whatsapp||"Not configured",socials.whatsapp||null],[MapPin,"Location",org.address||org.location||"Not configured",null],[Clock,"Office hours",org.officeHours||"Not configured",null]];
  return <main className="public-modern-page contact-modern-page"><section className="modern-hero modern-video-hero"><video className="modern-hero-video" autoPlay={!shouldSkipBackgroundVideo} muted loop playsInline preload={shouldSkipBackgroundVideo?"none":"metadata"} poster="/hero.jpg"><source src={heroVideo} type="video/mp4"/></video><div className="modern-hero-overlay"/><div className="modern-hero-content"><div><span className="modern-kicker">CONTACT US</span><h1>{settings?.website?.title||"We’d love to hear from you."}</h1><p>{settingsLoadingText(loading,settingsError,settings?.website?.subtitle)||"Send questions, feedback or enquiries through the official contact channel."}</p><div className="modern-hero-actions"><a className="modern-btn" href="#contact-form">Open message form <ArrowRight size={17}/></a><a className="modern-btn-secondary" href="/privacy-policy">Privacy policy</a></div></div><div className="modern-hero-panel"><div className="modern-panel-grid"><div className="modern-metric"><strong>Official channels</strong><span>Values below come from current settings</span></div><div className="modern-metric"><strong>Secure</strong><span>Form submission goes through the API</span></div><div className="modern-metric"><strong>Current</strong><span>SuperAdmin controls displayed contacts</span></div></div></div></div></section><section className="section" id="contact-form"><div className="section-container"><div className="contact-wrapper"><div className="contact-info"><p className="section-label">GET IN TOUCH</p><h2>Let’s start a conversation</h2><p className="contact-intro">{settingsError||"Use the official contacts below or send a message directly from the form."}</p>{items.map(([Icon,title,text,href])=><div className="contact-card" key={title}><div className="contact-icon"><Icon size={22}/></div><div><h4>{title}</h4>{href?<a href={href}>{text}</a>:<p>{text}</p>}</div></div>)}</div><div className="contact-form-card"><h2>Send us a message</h2>{status.message&&<div aria-live="polite" className={`contact-form-status ${status.type}`}>{status.type==="success"&&<CheckCircle2 size={18}/>} {status.message}</div>}<form className="contact-form" onSubmit={submit}><div className="input-grid"><label>Full Name<input type="text" value={form.fullName} onChange={onChange("fullName")} required/></label><label>Email Address<input type="email" value={form.email} onChange={onChange("email")} required/></label></div><label>Phone Number<input type="tel" value={form.phone} onChange={onChange("phone")}/></label><label>Subject<input type="text" value={form.subject} onChange={onChange("subject")} required/></label><label>Message<textarea rows="7" value={form.message} onChange={onChange("message")} required/></label><button disabled={busy} type="submit">{busy?<><Loader2 size={18}/> Sending...</>:<><Send size={18}/> Send Message</>}</button></form></div></div></div></section></main>;
}
function settingsLoadingText(loading,error,subtitle){if(loading)return "Loading current contact configuration…";if(error)return error;return subtitle;}
