import { LayoutDashboard, Users, Wallet, HandHeart, MessageCircle, UserRound, UserPlus, ClipboardList, ShieldCheck, DatabaseZap, Landmark, Bell, BarChart3, Globe2, ReceiptText, Activity, Settings2, FileText, Send, Banknote, UserCog, ShieldAlert } from "lucide-react";

export const dashboardMenus = {
  member: [
    { title: "Dashboard", icon: LayoutDashboard, path: "/member" },
    { title: "My Profile", icon: UserRound, path: "/member/profile" },
    { title: "Dependants", icon: Users, path: "/member/dependents" },
    { title: "Contributions", icon: Wallet, path: "/member/contributions" },
    { title: "Support & Claims", icon: HandHeart, path: "/member/claims" },
    { title: "Community", icon: Globe2, path: "/member/announcements" },
    { title: "Messages", icon: MessageCircle, path: "/member/messages" },
    { title: "Notifications", icon: Bell, path: "/member/notifications" },
    { title: "Benefits", icon: ShieldCheck, path: "/member/benefits" },
    { title: "Settings", icon: Settings2, path: "/member/settings" },
  ],
  admin: [
    { title: "Overview", icon: LayoutDashboard, path: "/admin" },
    { title: "Members", icon: Users, path: "/admin/members" },
    { title: "Contributions", icon: ReceiptText, path: "/admin/accounts" },
    { title: "Claims / Support", icon: HandHeart, path: "/admin/claims" },
    { title: "Disbursements", icon: Send, path: "/admin/accounts" },
    { title: "Communications", icon: MessageCircle, path: "/admin/messages" },
    { title: "Reports", icon: BarChart3, path: "/admin/reports" },
    { title: "Website Content", icon: Globe2, path: "/admin/website" },
    { title: "Notifications", icon: Bell, path: "/admin/notifications" },
    { title: "Settings", icon: Settings2, path: "/admin/settings" },
  ],
  superadmin: [
    { title: "Control Center", icon: LayoutDashboard, path: "/superadmin" },
    { title: "Members", icon: Users, path: "/superadmin/members" },
    { title: "Administrators", icon: UserPlus, path: "/superadmin/admins" },
    { title: "Financial Control", icon: Banknote, path: "/superadmin/accounts" },
    { title: "Disbursements", icon: Send, path: "/superadmin/accounts" },
    { title: "Support / Claims", icon: HandHeart, path: "/superadmin/claims" },
    { title: "Communications", icon: MessageCircle, path: "/superadmin/messages" },
    { title: "Website Management", icon: Globe2, path: "/superadmin/news" },
    { title: "Audit Logs", icon: ClipboardList, path: "/superadmin/audit" },
    { title: "System Health", icon: Activity, path: "/superadmin/system" },
    { title: "Security & Integrity", icon: ShieldAlert, path: "/superadmin/data-integrity" },
    { title: "Policies", icon: FileText, path: "/superadmin/policies" },
    { title: "Constitution", icon: Landmark, path: "/superadmin/constitution" },
    { title: "Settings", icon: UserCog, path: "/superadmin/settings" },
  ],
};
