import {
  UserRound, Users, FileText, ShieldCheck, Wallet, Smartphone, ReceiptText,
  HandHeart, ClipboardList, MessageCircle, Megaphone, Bell, Vote, Newspaper,
  UserPlus, Settings, Landmark, DatabaseZap, Activity, Globe2, Image,
  HelpCircle, Phone, BarChart3, HeartPulse
} from "lucide-react";

export const portalSections = {
  member: [
    {
      key: "account",
      title: "My Account",
      eyebrow: "MEMBER ACCOUNT",
      description: "Manage your personal information, family records and account security.",
      icon: UserRound,
      path: "/member/account",
      links: [
        ["Profile", "Your personal and membership details.", "/member/profile", UserRound],
        ["Dependents", "Manage people linked to your membership.", "/member/dependents", Users],
        ["Documents", "Upload and review your membership documents inside Profile.", "/member/profile#documents", FileText],
        ["Security", "Password and account-security controls.", "/member/settings", ShieldCheck],
      ],
    },
    {
      key: "money",
      title: "Money & Contributions",
      eyebrow: "MONEY & M-PESA",
      description: "Keep contributions, account activity and M-PESA records together in one place.",
      icon: Wallet,
      path: "/member/money",
      links: [
        ["Accounts", "View contribution balances and account activity.", "/member/accounts", Wallet],
        ["Contributions", "Review your contribution history and totals.", "/member/contributions", ReceiptText],
        ["M-PESA Records", "Review payment records linked to your account.", "/member/mpesa-records", Smartphone],
      ],
    },
    {
      key: "support",
      title: "Support & Claims",
      eyebrow: "MEMBER SUPPORT",
      description: "Request assistance and track support or claim decisions from one workflow.",
      icon: HandHeart,
      path: "/member/support-center",
      links: [
        ["Request Support", "Start a new welfare/support request.", "/member/support", HandHeart],
        ["My Requests", "Review active and previous support requests.", "/member/support?view=requests", ClipboardList],
        ["Claims", "Track claims, status and community-support matters.", "/member/claims", ClipboardList],
        ["Benefits", "See the assistance programmes available to members.", "/member/benefits", HeartPulse],
      ],
    },
    {
      key: "community",
      title: "Community",
      eyebrow: "COMMUNITY & COMMUNICATION",
      description: "Stay connected with members, leaders and the latest Benevolent MIDAX communications.",
      icon: MessageCircle,
      path: "/member/community",
      links: [
        ["Chat", "Private member and leadership conversations.", "/member/messages", MessageCircle],
        ["Announcements", "Official organizational announcements.", "/member/announcements", Megaphone],
        ["Notifications", "Your latest alerts and action reminders.", "/member/notifications", Bell],
        ["Polls", "Participate in community polls and view results.", "/member/polls", Vote],
        ["Feedback", "Share feedback with Benevolent MIDAX.", "/member/feedback", FileText],
      ],
    },
    {
      key: "help",
      title: "Help & Guide",
      eyebrow: "HELP",
      description: "Get guidance on using the member portal and contact the organization when needed.",
      icon: HelpCircle,
      path: "/member/help",
      links: [
        ["User Guide", "Learn how the main member tools work.", "/member/guide", HelpCircle],
        ["Contact", "Reach the organization for assistance.", "/contact", Phone],
        ["Feedback", "Report an issue or share an experience.", "/member/feedback", FileText],
      ],
    },
  ],
  admin: [
    {
      key: "operations",
      title: "People & Operations",
      eyebrow: "LEADERSHIP OPERATIONS",
      description: "Handle member oversight, verification, welfare support and claims as an organizational leader.",
      icon: Users,
      path: "/admin/operations",
      links: [
        ["Members", "Review and manage member records.", "/admin/members", Users],
        ["Verification", "Review members awaiting organizational verification.", "/admin/members?view=pending", ShieldCheck],
        ["Support", "Review member welfare/support requests.", "/admin/support", HandHeart],
        ["Claims", "Review and progress claims.", "/admin/claims", ClipboardList],
      ],
    },
    {
      key: "finance",
      title: "Finance",
      eyebrow: "BENEVELENT FINANCE",
      description: "Review organizational accounts, contributions, payments and support-related finance workflows.",
      icon: Wallet,
      path: "/admin/finance-center",
      links: [
        ["Accounts", "Open the canonical organizational account ledger.", "/admin/accounts", Wallet],
        ["Contributions", "Review contribution activity inside Accounts.", "/admin/accounts?tab=contributions", ReceiptText],
        ["Payments", "Review payment activity and M-PESA records.", "/admin/accounts?tab=mpesa", Smartphone],
        ["Community Support", "Review support-related financial activity.", "/admin/support", HandHeart],
      ],
    },
    {
      key: "communications",
      title: "Communications",
      eyebrow: "LEADERSHIP COMMUNICATIONS",
      description: "Manage messages, announcements, notifications and community engagement.",
      icon: MessageCircle,
      path: "/admin/communications",
      links: [
        ["Messages", "Communicate with members through the leadership channel.", "/admin/messages", MessageCircle],
        ["Announcements", "Publish organizational announcements.", "/admin/announcements", Megaphone],
        ["Notifications", "Review and manage notifications.", "/admin/notifications", Bell],
        ["Polls", "Create and manage community polls.", "/admin/polls", Vote],
        ["Feedback", "Review member feedback.", "/admin/feedback", FileText],
      ],
    },
    {
      key: "website",
      title: "Website & Communications",
      eyebrow: "CONTENT",
      description: "Manage the website-facing content available to your leadership role.",
      icon: Newspaper,
      path: "/admin/website",
      links: [
        ["Website", "Daily website and communication controls.", "/admin/website", Globe2],
        ["Announcements", "Publish current notices.", "/admin/announcements", Megaphone],
      ],
    },
    {
      key: "reports",
      title: "Reports",
      eyebrow: "REPORTS & OVERSIGHT",
      description: "Open the reporting workspace and review organizational activity by area.",
      icon: BarChart3,
      path: "/admin/reports",
      links: [
        ["Member Reports", "Membership and verification reporting.", "/admin/reports?report=members", Users],
        ["Finance Reports", "Contribution and payment reporting.", "/admin/reports?report=finance", Wallet],
        ["Support Reports", "Support workflow reporting.", "/admin/reports?report=support", HandHeart],
        ["Claims Reports", "Claim lifecycle reporting.", "/admin/reports?report=claims", ClipboardList],
      ],
    },
    {
      key: "leadership",
      title: "Leadership & Constitution",
      eyebrow: "GOVERNANCE",
      description: "Keep organizational leadership and constitutional work distinct from technical system administration.",
      icon: Landmark,
      path: "/admin/leadership",
      links: [
        ["Constitution", "Review governing organizational rules.", "/constitution", Landmark],
        ["Leadership", "Leadership responsibilities and visibility.", "/leaders", Users],
        ["Governance", "Open leadership governance resources.", "/admin/leadership?view=governance", ShieldCheck],
      ],
    },
  ],
  superadmin: [
    {
      key: "people",
      title: "People & Access",
      eyebrow: "PEOPLE & ACCESS",
      description: "Manage administrators, leaders, members and role-based access from one section.",
      icon: Users,
      path: "/superadmin/people",
      links: [
        ["Administrators / Leaders", "Manage technical administrator access.", "/superadmin/admins", UserPlus],
        ["Members", "Inspect member records and integrity.", "/superadmin/members", Users],
        ["Leaders", "Manage leadership-facing records.", "/superadmin/leaders", UserRound],
      ],
    },
    {
      key: "governance",
      title: "Governance",
      eyebrow: "GOVERNANCE",
      description: "Keep constitutional, policy and audit concerns together without mixing them into everyday operations.",
      icon: Landmark,
      path: "/superadmin/governance",
      links: [
        ["Constitution", "Review and maintain constitutional content.", "/superadmin/constitution", Landmark],
        ["Policies", "Manage reusable organizational policies.", "/superadmin/policies", FileText],
        ["Audit", "Review auditable system and organizational actions.", "/superadmin/audit", ClipboardList],
      ],
    },
    {
      key: "finance",
      title: "Finance & Assistance",
      eyebrow: "FINANCE & SUPPORT",
      description: "Control financial records, contributions, support workflows, claims and disbursement-related tools.",
      icon: Wallet,
      path: "/superadmin/finance-center",
      links: [
        ["Accounts", "Open the canonical accounts workspace.", "/superadmin/accounts", Wallet],
        ["Claims", "Review organizational claims.", "/superadmin/claims", ClipboardList],
        ["Support", "Review support workflows.", "/superadmin/support", HandHeart],
      ],
    },
    {
      key: "communications",
      title: "Website & Communications",
      eyebrow: "WEBSITE & COMMUNICATIONS",
      description: "Manage public content and organizational communication without putting every tool into the sidebar.",
      icon: Newspaper,
      path: "/superadmin/communications",
      links: [
        ["News", "Manage public news and events content.", "/superadmin/news", Newspaper],
        ["Leaders", "Manage public leadership presentation.", "/superadmin/leaders", Users],
        ["Policies", "Publish and maintain policy content.", "/superadmin/policies", FileText],
        ["Messages", "Review system and leadership communications.", "/superadmin/messages", MessageCircle],
        ["Feedback", "Review member feedback collections.", "/superadmin/feedback", FileText],
      ],
    },
    {
      key: "system",
      title: "System & Diagnostics",
      eyebrow: "SYSTEM",
      description: "Technical controls belong here: integrity, health, notifications, security and system settings.",
      icon: ShieldCheck,
      path: "/superadmin/system-center",
      links: [
        ["Data Integrity", "Detect controlled data-integrity problems.", "/superadmin/data-integrity", DatabaseZap],
        ["Health", "Review system health indicators.", "/superadmin/system", Activity],
        ["Notifications", "Inspect notification operations.", "/superadmin/notifications", Bell],
        ["Security", "Open security and access controls.", "/superadmin/settings?tab=security", ShieldCheck],
        ["Branding", "Manage technical branding settings.", "/superadmin/settings?tab=branding", Image],
      ],
    },
    {
      key: "settings",
      title: "Settings",
      eyebrow: "SETTINGS",
      description: "Open the SuperAdmin settings workspace for configuration that belongs to technical system authority.",
      icon: Settings,
      path: "/superadmin/settings-center",
      links: [
        ["System Settings", "Portal-wide configuration and system preferences.", "/superadmin/settings", Settings],
        ["Password", "Change the current SuperAdmin password.", "/superadmin/password", ShieldCheck],
      ],
    },
  ],
};

