import { useEffect, useMemo, useState } from "react";
import DashboardLayout from "../../layouts/DashboardLayout";
import API, { resolveApiUrl } from "../../services/api";
import "../../styles/portalModule.css";

const STAGES = ["Pending", "Under Review", "Documents Required", "Eligibility Review", "Approval Review", "Approved", "Disbursement Pending", "Paid", "Completed", "Rejected", "Cancelled", "Closed"];
const money = (v) => new Intl.NumberFormat("en-KE", { style:"currency", currency:"KES", maximumFractionDigits:0 }).format(Number(v || 0));
const formatDate = (v) => v ? new Date(v).toLocaleDateString("en-KE", {day:"2-digit",month:"short",year:"numeric"}) : "—";
const typeLabel = (v) => String(v || "support").replace(/^./, c => c.toUpperCase());

export default function AdminClaims(){
  const [claims,setClaims]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[busy,setBusy]=useState(""),[selected,setSelected]=useState(null),[stage,setStage]=useState(""),[remarks,setRemarks]=useState(""),[approvedAmount,setApprovedAmount]=useState("");
  const load=async()=>{try{setLoading(true);setError("");const {data}=await API.get("/claims");setClaims(Array.isArray(data?.claims)?data.claims:[]);}catch(e){setError(e.response?.data?.message||e.message||"Unable to load claims.");}finally{setLoading(false);}};
  useEffect(()=>{load();},[]);
  const grouped=useMemo(()=>claims.reduce((a,c)=>{const key=c.status||"Pending";(a[key]??=[]).push(c);return a;},{}),[claims]);
  const open=(claim)=>{setSelected(claim);setStage(claim.status||"Pending");setRemarks("");setApprovedAmount(String(claim.approvedAmount||claim.requestedAmount||""));};
  const saveStage=async()=>{if(!selected||!stage)return;try{setBusy(selected._id);const payload={status:stage,remarks};if(stage==="Approved")payload.approvedAmount=Number(approvedAmount||selected.requestedAmount||0);if(stage==="Rejected")payload.rejectionReason=remarks;const {data}=await API.put(`/claims/${selected.sourceType}/${selected._id}/stage`,payload);if(!data?.success)throw new Error(data?.message||"Could not update claim.");setSelected(null);await load();}catch(e){setError(e.response?.data?.message||e.message||"Unable to update claim.");}finally{setBusy("");}};
  const openDocument=async(claim,url)=>{if(!url)return;window.open(url.startsWith("http")?url:resolveApiUrl(url),"_blank","noopener,noreferrer");};
  return <DashboardLayout><div className="portal-module">
    <header className="portal-module-header"><div><span>PROFESSIONAL CLAIM REVIEW</span><h1>Claims & Support</h1><p>Admin and SuperAdmin follow the same controlled review stages. Every movement is recorded and immediately reflected in the member portal.</p></div><button className="portal-btn" onClick={load} disabled={loading}>{loading?"Refreshing…":"Refresh"}</button></header>
    {error&&<div className="portal-alert">{error}</div>}
    <section className="portal-stat-grid">{["Pending","Under Review","Documents Required","Eligibility Review","Approval Review","Approved","Disbursement Pending","Paid","Completed"].map(s=><div className="portal-stat" key={s}><span>{s}</span><strong>{grouped[s]?.length||0}</strong></div>)}</section>
    {loading?<div className="portal-empty">Loading claims…</div>:claims.length===0?<div className="portal-empty"><h3>No claims available</h3><p>Member applications will appear here automatically.</p></div>:<section className="portal-grid two">{claims.map(c=><article className="portal-panel" key={`${c.sourceType}-${c._id}`} style={{margin:0}}><div style={{display:"flex",justifyContent:"space-between",gap:12,alignItems:"start"}}><div><span className="portal-badge">{typeLabel(c.supportType)}</span><h2>{c.description||c.purpose||c.caseDescription||"Support application"}</h2><p>{c.member?.fullName||c.member?.memberNumber||"Member"} • {formatDate(c.createdAt||c.applicationDate)}</p></div><span className="portal-badge">{c.status||"Pending"}</span></div><div className="portal-stat-grid"><div className="portal-stat"><span>Requested</span><strong>{money(c.requestedAmount)}</strong></div><div className="portal-stat"><span>Approved</span><strong>{money(c.approvedAmount)}</strong></div></div>{c.remarks&&<p>{c.remarks}</p>}<div style={{display:"flex",gap:8,flexWrap:"wrap"}}>{(c.documents||[]).map((d,i)=>{const u=typeof d==="string"?d:d?.fileUrl||d?.url;return u?<button key={i} className="portal-btn secondary" onClick={()=>openDocument(c,u)}>Document {i+1}</button>:null})}</div><div className="portal-actions" style={{marginTop:12}}><button className="portal-btn" onClick={()=>open(c)}>Review / update</button></div>{Array.isArray(c.timeline)&&c.timeline.length>0&&<div style={{marginTop:14}}><strong>Latest review</strong><p>{c.timeline[c.timeline.length-1]?.status}: {c.timeline[c.timeline.length-1]?.remarks||"—"}</p></div>}</article>)}</section>}
    {selected&&<div role="dialog" aria-modal="true" style={{position:"fixed",inset:0,background:"rgba(10,16,24,.58)",display:"grid",placeItems:"center",padding:16,zIndex:10000}}><section className="portal-panel" style={{width:"min(760px,100%)",maxHeight:"90vh",overflow:"auto"}}><h2>Review {typeLabel(selected.supportType)} claim</h2><p><strong>{selected.member?.fullName||"Member"}</strong> • {money(selected.requestedAmount)} requested</p><label style={{display:"grid",gap:6,fontWeight:700}}>Stage<select value={stage} onChange={e=>setStage(e.target.value)}>{STAGES.map(x=><option key={x} value={x}>{x}</option>)}</select></label>{stage==="Approved"&&<label style={{display:"grid",gap:6,fontWeight:700,marginTop:12}}>Approved amount<input type="number" min="0" value={approvedAmount} onChange={e=>setApprovedAmount(e.target.value)}/></label>}<label style={{display:"grid",gap:6,fontWeight:700,marginTop:12}}>Professional review notes<textarea rows="5" value={remarks} onChange={e=>setRemarks(e.target.value)} placeholder="Record what was checked, what is missing, the eligibility finding, or the approval/rejection reason."/></label><div className="portal-actions" style={{marginTop:16}}><button className="portal-btn" onClick={saveStage} disabled={busy===selected._id}>{busy===selected._id?"Saving…":"Save stage"}</button><button className="portal-btn secondary" onClick={()=>setSelected(null)}>Cancel</button></div></section></div>}
  </div></DashboardLayout>
}
